"""
Frida Script Generator
======================
Automatically generates Frida instrumentation scripts based on
decompiled application source code analysis.
Produces ready-to-execute JavaScript hooks for dynamic analysis.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

from mobile_tool_registry import UnifiedFinding  # noqa: F401 — re-exported for consumers

log = logging.getLogger("oneinfinity.mobile.frida_script_generator")


# ─────────────────────────────────────────────────────────────────────────────
#  Data Classes
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class HookTarget:
    class_name: str
    method_name: str
    hook_type: str          # "auth" | "crypto" | "ssl" | "network" | "storage" | "root" | "custom"
    priority: int = 5       # 1 (low) – 10 (critical)
    description: str = ""


@dataclass
class FridaScript:
    name: str
    description: str
    targets: List[HookTarget] = field(default_factory=list)
    script_content: str = ""
    platform: str = "android"
    auto_run: bool = False


# ─────────────────────────────────────────────────────────────────────────────
#  Generator
# ─────────────────────────────────────────────────────────────────────────────

class FridaScriptGenerator:
    """
    Generates complete, ready-to-run Frida JavaScript instrumentation scripts
    for Android (and limited iOS) applications.
    """

    def __init__(self) -> None:
        pass

    # ── Main entry ────────────────────────────────────────────────────────────

    def generate_from_app_model(
        self,
        app_model,                  # AppModel from mobile_ai_reverse_engineer
        decompiled_dir: str = "",
        platform: str = "android",
    ) -> List[FridaScript]:
        """
        Generate all relevant Frida scripts based on an AppModel.
        Returns a list of complete FridaScript objects.
        """
        scripts: List[FridaScript] = []

        # Always generate SSL bypass and root bypass
        scripts.append(self.generate_ssl_bypass_script(platform=platform))
        scripts.append(self.generate_root_bypass_script())
        scripts.append(self.generate_anti_debug_bypass())
        scripts.append(self.generate_storage_hook_script())

        # App-model-driven scripts
        auth_classes = getattr(app_model, "auth_classes", [])
        crypto_classes = getattr(app_model, "crypto_classes", [])
        network_classes = getattr(app_model, "network_classes", [])

        if auth_classes:
            scripts.append(self.generate_auth_hook_script(auth_classes))
        if crypto_classes:
            scripts.append(self.generate_crypto_hook_script(crypto_classes))
        if network_classes:
            scripts.append(self.generate_network_hook_script(network_classes))

        log.info("Generated %d Frida scripts for platform=%s", len(scripts), platform)
        return scripts

    # ── SSL Bypass ────────────────────────────────────────────────────────────

    def generate_ssl_bypass_script(self, platform: str = "android") -> FridaScript:
        """
        Complete SSL pinning bypass for Android (TrustManager, OkHttp3,
        SSLContext, Conscrypt, Flutter) and iOS (SecTrustEvaluate).
        """
        targets = [
            HookTarget("javax.net.ssl.X509TrustManager", "checkServerTrusted", "ssl", 10,
                       "Bypass custom TrustManager certificate validation"),
            HookTarget("okhttp3.CertificatePinner", "check", "ssl", 10,
                       "Bypass OkHttp3 certificate pinning"),
            HookTarget("javax.net.ssl.SSLContext", "init", "ssl", 9,
                       "Replace SSLContext with permissive version"),
            HookTarget("com.android.org.conscrypt.TrustManagerImpl", "verifyChain", "ssl", 9,
                       "Bypass Conscrypt chain verification"),
        ]

        android_js = r"""
// ============================================================
// SSL Pinning Bypass — Frida Script (Android)
// Generated by FridaScriptGenerator
// ============================================================

'use strict';

function emit(tag, data) {
    var out = JSON.stringify({ tag: tag, data: data, ts: new Date().toISOString() });
    console.log('[FRIDA_FINDING] ' + out);
}

Java.perform(function () {

    // ── 1. Permissive TrustManager ────────────────────────────────────────
    try {
        var X509TrustManager = Java.use('javax.net.ssl.X509TrustManager');
        var SSLContext = Java.use('javax.net.ssl.SSLContext');

        var TrustAllCerts = Java.registerClass({
            name: 'com.frida.bypass.TrustAllManager',
            implements: [X509TrustManager],
            methods: {
                checkClientTrusted: function (chain, authType) { },
                checkServerTrusted: function (chain, authType) {
                    emit('ssl_bypass', { method: 'checkServerTrusted', authType: authType });
                },
                getAcceptedIssuers: function () { return []; }
            }
        });

        var sslCtx = SSLContext.getInstance('TLS');
        sslCtx.init(null, [TrustAllCerts.$new()], null);
        SSLContext.getDefault.implementation = function () {
            emit('ssl_bypass', { method: 'SSLContext.getDefault patched' });
            return sslCtx;
        };
        console.log('[SSL-Bypass] Permissive TrustManager installed.');
    } catch (e) {
        console.log('[SSL-Bypass] TrustManager bypass failed: ' + e.message);
    }

    // ── 2. OkHttp3 CertificatePinner ─────────────────────────────────────
    try {
        var CertificatePinner = Java.use('okhttp3.CertificatePinner');
        CertificatePinner.check.overload('java.lang.String', 'java.util.List').implementation = function (hostname, peerCertificates) {
            emit('ssl_bypass', { method: 'OkHttp3.CertificatePinner.check', hostname: hostname });
            console.log('[SSL-Bypass] OkHttp3 pin bypassed for: ' + hostname);
        };
        // Older overload
        CertificatePinner.check.overload('java.lang.String', '[Ljava.security.cert.Certificate;').implementation = function (hostname, certs) {
            emit('ssl_bypass', { method: 'OkHttp3.CertificatePinner.check (legacy)', hostname: hostname });
        };
        console.log('[SSL-Bypass] OkHttp3 CertificatePinner hooked.');
    } catch (e) {
        console.log('[SSL-Bypass] OkHttp3 hook failed (may not be present): ' + e.message);
    }

    // ── 3. OkHttp3 match() ────────────────────────────────────────────────
    try {
        var CertificatePinner2 = Java.use('okhttp3.CertificatePinner$Builder');
        // No-op; rely on check() override above.
    } catch (e) { }

    // ── 4. TrustManagerImpl (Conscrypt) ───────────────────────────────────
    try {
        var TrustManagerImpl = Java.use('com.android.org.conscrypt.TrustManagerImpl');
        TrustManagerImpl.verifyChain.implementation = function (untrustedChain, trustAnchorChain, host, clientAuth, ocspData, tlsSctData) {
            emit('ssl_bypass', { method: 'Conscrypt.verifyChain', host: host });
            console.log('[SSL-Bypass] Conscrypt verifyChain bypassed for: ' + host);
            return untrustedChain;
        };
        console.log('[SSL-Bypass] Conscrypt TrustManagerImpl hooked.');
    } catch (e) {
        console.log('[SSL-Bypass] Conscrypt hook failed (may not be present): ' + e.message);
    }

    // ── 5. HttpsURLConnection HostnameVerifier ────────────────────────────
    try {
        var HttpsURLConnection = Java.use('javax.net.ssl.HttpsURLConnection');
        HttpsURLConnection.setDefaultHostnameVerifier.implementation = function (verifier) {
            emit('ssl_bypass', { method: 'HttpsURLConnection.setDefaultHostnameVerifier replaced' });
            // Install permissive verifier
            var AllowAllHostnameVerifier = Java.registerClass({
                name: 'com.frida.bypass.AllHostnameVerifier',
                implements: [Java.use('javax.net.ssl.HostnameVerifier')],
                methods: {
                    verify: function (hostname, session) {
                        return true;
                    }
                }
            });
            this.setDefaultHostnameVerifier(AllowAllHostnameVerifier.$new());
        };
        console.log('[SSL-Bypass] HttpsURLConnection HostnameVerifier hooked.');
    } catch (e) {
        console.log('[SSL-Bypass] HostnameVerifier hook failed: ' + e.message);
    }

    // ── 6. Flutter SSL (native layer, best-effort) ────────────────────────
    try {
        var flutterLib = 'libflutter.so';
        var ssl_verify_ptr = Module.findExportByName(flutterLib, 'ssl_crypto_x509_session_verify_cert_chain');
        if (ssl_verify_ptr) {
            Interceptor.attach(ssl_verify_ptr, {
                onLeave: function (retval) {
                    emit('ssl_bypass', { method: 'Flutter ssl_crypto_x509_session_verify_cert_chain patched' });
                    retval.replace(1);  // return success
                }
            });
            console.log('[SSL-Bypass] Flutter SSL verify hooked.');
        }
    } catch (e) {
        console.log('[SSL-Bypass] Flutter SSL hook skipped: ' + e.message);
    }

    console.log('[SSL-Bypass] All SSL bypasses installed.');
});
"""

        ios_js = r"""
// ============================================================
// SSL Bypass — iOS (SecTrustEvaluate)
// ============================================================
'use strict';

function emit(tag, data) {
    console.log('[FRIDA_FINDING] ' + JSON.stringify({ tag: tag, data: data }));
}

// Bypass SecTrustEvaluate
var SecTrustEvaluate_ptr = Module.findExportByName('Security', 'SecTrustEvaluate');
if (SecTrustEvaluate_ptr) {
    Interceptor.attach(SecTrustEvaluate_ptr, {
        onLeave: function (retval) {
            emit('ssl_bypass', { method: 'SecTrustEvaluate', original: retval.toInt32() });
            retval.replace(0);  // errSecSuccess
        }
    });
    console.log('[SSL-Bypass] SecTrustEvaluate hooked.');
}

// Bypass SecTrustEvaluateWithError (iOS 12+)
var SecTrustEvaluateWithError_ptr = Module.findExportByName('Security', 'SecTrustEvaluateWithError');
if (SecTrustEvaluateWithError_ptr) {
    Interceptor.attach(SecTrustEvaluateWithError_ptr, {
        onLeave: function (retval) {
            emit('ssl_bypass', { method: 'SecTrustEvaluateWithError' });
            retval.replace(1);  // true = trusted
        }
    });
    console.log('[SSL-Bypass] SecTrustEvaluateWithError hooked.');
}
"""

        script_js = android_js if platform == "android" else ios_js
        script_js = self._build_js_header() + script_js

        return FridaScript(
            name="ssl_bypass",
            description="Bypass SSL certificate pinning for TrustManager, OkHttp3, Conscrypt, Flutter, and iOS SecTrustEvaluate",
            targets=targets,
            script_content=script_js,
            platform=platform,
            auto_run=True,
        )

    # ── Root Bypass ───────────────────────────────────────────────────────────

    def generate_root_bypass_script(self) -> FridaScript:
        """
        Hook common root/jailbreak detection libraries:
        RootBeer, SafetyNet, su binary checks, Build.TAGS.
        """
        targets = [
            HookTarget("com.scottyab.rootbeer.RootBeer", "isRooted", "root", 9, "RootBeer root check"),
            HookTarget("java.lang.Runtime", "exec", "root", 8, "Block su execution"),
        ]

        script_js = r"""
// ============================================================
// Root / Jailbreak Detection Bypass
// ============================================================
'use strict';

function emit(tag, data) {
    console.log('[FRIDA_FINDING] ' + JSON.stringify({ tag: tag, data: data }));
}

Java.perform(function () {

    // ── 1. RootBeer ──────────────────────────────────────────────────────
    try {
        var RootBeer = Java.use('com.scottyab.rootbeer.RootBeer');
        var rootMethods = ['isRooted', 'isRootedWithoutBusyBox', 'detectRootManagementApps',
                           'detectPotentiallyDangerousApps', 'checkForSuBinary',
                           'checkSuExists', 'checkForRWPaths', 'checkDangerousProps',
                           'checkRootThroughNativeCode'];
        rootMethods.forEach(function (method) {
            try {
                RootBeer[method].implementation = function () {
                    emit('root_bypass', { library: 'RootBeer', method: method });
                    return false;
                };
            } catch (e) { }
        });
        console.log('[Root-Bypass] RootBeer hooked.');
    } catch (e) {
        console.log('[Root-Bypass] RootBeer not found: ' + e.message);
    }

    // ── 2. Build.TAGS ────────────────────────────────────────────────────
    try {
        var Build = Java.use('android.os.Build');
        Object.defineProperty(Build, 'TAGS', {
            get: function () { return 'release-keys'; }
        });
        console.log('[Root-Bypass] Build.TAGS patched to release-keys.');
    } catch (e) {
        console.log('[Root-Bypass] Build.TAGS patch failed: ' + e.message);
    }

    // ── 3. File existence checks (su, busybox) ────────────────────────────
    try {
        var File = Java.use('java.io.File');
        var SU_PATHS = [
            '/system/app/Superuser.apk', '/system/xbin/su', '/system/bin/su',
            '/sbin/su', '/su/bin/su', '/data/local/xbin/su', '/data/local/bin/su',
            '/data/local/su', '/system/sd/xbin/su', '/system/bin/failsafe/su',
            '/system/app/SuperSU.apk', '/system/app/Magisk.apk'
        ];
        File.exists.implementation = function () {
            var path = this.getAbsolutePath();
            if (SU_PATHS.indexOf(path) >= 0) {
                emit('root_bypass', { method: 'File.exists', path: path });
                return false;
            }
            return this.exists();
        };
        console.log('[Root-Bypass] File.exists() patched for su paths.');
    } catch (e) {
        console.log('[Root-Bypass] File.exists hook failed: ' + e.message);
    }

    // ── 4. Runtime.exec("su") ────────────────────────────────────────────
    try {
        var Runtime = Java.use('java.lang.Runtime');
        Runtime.exec.overload('java.lang.String').implementation = function (cmd) {
            if (cmd && cmd.indexOf('su') >= 0) {
                emit('root_bypass', { method: 'Runtime.exec', cmd: cmd });
                var IOException = Java.use('java.io.IOException');
                throw IOException.$new('Permission denied (root bypass)');
            }
            return this.exec(cmd);
        };
        Runtime.exec.overload('[Ljava.lang.String;').implementation = function (cmdArray) {
            if (cmdArray && cmdArray.length > 0 && cmdArray[0].indexOf('su') >= 0) {
                emit('root_bypass', { method: 'Runtime.exec[]', cmd: cmdArray[0] });
                var IOException = Java.use('java.io.IOException');
                throw IOException.$new('Permission denied (root bypass)');
            }
            return this.exec(cmdArray);
        };
        console.log('[Root-Bypass] Runtime.exec hooked for su commands.');
    } catch (e) {
        console.log('[Root-Bypass] Runtime.exec hook failed: ' + e.message);
    }

    // ── 5. SafetyNet / Play Integrity ─────────────────────────────────────
    try {
        var SafetyNetClient = Java.use('com.google.android.gms.safetynet.SafetyNetClient');
        SafetyNetClient.attest.implementation = function (nonce, apiKey) {
            emit('root_bypass', { method: 'SafetyNet.attest bypassed' });
            // Return a task-like stub; real bypass requires spoofing the JWS response
            return this.attest(nonce, apiKey);
        };
    } catch (e) { }

    // ── 6. SystemProperties checks ────────────────────────────────────────
    try {
        var SystemProperties = Java.use('android.os.SystemProperties');
        SystemProperties.get.overload('java.lang.String').implementation = function (key) {
            var val = this.get(key);
            if (key === 'ro.debuggable' || key === 'ro.secure') {
                emit('root_bypass', { method: 'SystemProperties.get', key: key, original: val });
                return key === 'ro.debuggable' ? '0' : '1';
            }
            return val;
        };
        console.log('[Root-Bypass] SystemProperties patched.');
    } catch (e) {
        console.log('[Root-Bypass] SystemProperties hook failed: ' + e.message);
    }

    console.log('[Root-Bypass] All root detection bypasses installed.');
});
"""
        return FridaScript(
            name="root_bypass",
            description="Bypass RootBeer, SafetyNet, su binary checks, Build.TAGS and SystemProperties root detection",
            targets=targets,
            script_content=self._build_js_header() + script_js,
            platform="android",
            auto_run=True,
        )

    # ── Auth Hook ─────────────────────────────────────────────────────────────

    def generate_auth_hook_script(self, auth_classes: List[str]) -> FridaScript:
        """
        Generate hooks for each auth-related class to log credentials,
        tokens, and auth results.
        """
        targets = [
            HookTarget(cls, "*", "auth", 9, f"Hook auth class {cls}")
            for cls in auth_classes[:20]
        ]

        class_hooks = ""
        for cls in auth_classes[:20]:
            class_hooks += self._build_auth_class_hook(cls)

        script_js = f"""
// ============================================================
// Authentication Hook Script
// Hooked classes: {', '.join(auth_classes[:20])}
// ============================================================
'use strict';

function emit(tag, data) {{
    console.log('[FRIDA_FINDING] ' + JSON.stringify({{ tag: tag, data: data, ts: new Date().toISOString() }}));
}}

function decodeJwt(token) {{
    try {{
        if (typeof token !== 'string' || token.split('.').length !== 3) return null;
        var parts = token.split('.');
        var header = JSON.parse(Java.use('android.util.Base64').decode(
            parts[0], 0).map(function(b) {{ return String.fromCharCode(b & 0xff); }}).join(''));
        var payload = JSON.parse(Java.use('android.util.Base64').decode(
            parts[1], 0).map(function(b) {{ return String.fromCharCode(b & 0xff); }}).join(''));
        return {{ header: header, payload: payload }};
    }} catch (e) {{ return null; }}
}}

Java.perform(function () {{

    // ── Generic method argument logger ────────────────────────────────────
    function hookAuthMethod(className, methodName, overloadArgs) {{
        try {{
            var cls = Java.use(className);
            var methodRef = cls[methodName];
            if (!methodRef) return;
            var impl = function() {{
                var args = Array.prototype.slice.call(arguments);
                var argStrings = args.map(function(a) {{
                    if (a === null || a === undefined) return String(a);
                    var s = String(a);
                    // Detect JWT
                    if (s.split('.').length === 3) {{
                        var jwt = decodeJwt(s);
                        if (jwt) emit('jwt_found', {{ class: className, method: methodName, jwt: jwt }});
                    }}
                    return s.substring(0, 200);
                }});
                emit('auth_call', {{ class: className, method: methodName, args: argStrings }});
                var ret = this[methodName].apply(this, args);
                emit('auth_return', {{ class: className, method: methodName, result: String(ret).substring(0, 200) }});
                return ret;
            }};
            if (overloadArgs && methodRef.overload) {{
                methodRef.overload.apply(methodRef, overloadArgs).implementation = impl;
            }} else {{
                methodRef.implementation = impl;
            }}
            console.log('[Auth-Hook] Hooked ' + className + '.' + methodName);
        }} catch (e) {{
            console.log('[Auth-Hook] Failed to hook ' + className + '.' + methodName + ': ' + e.message);
        }}
    }}

{class_hooks}

    console.log('[Auth-Hook] All authentication hooks installed.');
}});
"""
        return FridaScript(
            name="auth_hooks",
            description=f"Hook {len(auth_classes)} authentication classes to capture credentials and tokens",
            targets=targets,
            script_content=self._build_js_header() + script_js,
            platform="android",
            auto_run=False,
        )

    def _build_auth_class_hook(self, class_name: str) -> str:
        """Generate JS hook stanza for a single auth class."""
        safe_name = class_name.replace(".", "_").replace("$", "_")
        auth_methods = ["login", "authenticate", "verify", "validateToken", "checkToken",
                        "getToken", "refreshToken", "signIn", "doLogin", "checkPassword"]
        lines = [f"    // ── {class_name} ──"]
        for method in auth_methods:
            lines.append(f"    hookAuthMethod('{class_name}', '{method}');")
        # Also try to enumerate all declared methods at runtime
        lines.append(f"""
    try {{
        var {safe_name} = Java.use('{class_name}');
        var methods = {safe_name}.class.getDeclaredMethods();
        methods.forEach(function (m) {{
            var methodName = m.getName();
            var paramTypes = m.getParameterTypes().map(function(p) {{ return p.getName(); }});
            try {{
                {safe_name}[methodName].overload.apply({safe_name}[methodName], paramTypes).implementation = function() {{
                    var args = Array.prototype.slice.call(arguments).map(String);
                    emit('auth_method', {{ class: '{class_name}', method: methodName, args: args.map(function(a){{return a.substring(0,100);}}) }});
                    return this[methodName].apply(this, arguments);
                }};
            }} catch (e) {{ /* skip overloads that fail */ }}
        }});
    }} catch (e) {{ console.log('[Auth-Hook] Reflection hook for {class_name} failed: ' + e.message); }}
""")
        return "\n".join(lines) + "\n"

    # ── Crypto Hook ───────────────────────────────────────────────────────────

    def generate_crypto_hook_script(self, crypto_classes: List[str]) -> FridaScript:
        """
        Hook MessageDigest, Cipher, SecretKeySpec, Mac to log cryptographic
        operations and detect weak algorithms, hardcoded keys, static IVs.
        """
        targets = [
            HookTarget("javax.crypto.Cipher", "doFinal", "crypto", 9, "Log all cipher operations"),
            HookTarget("java.security.MessageDigest", "digest", "crypto", 8, "Log all hash operations"),
            HookTarget("javax.crypto.spec.SecretKeySpec", "<init>", "crypto", 10, "Detect hardcoded keys"),
        ]

        weak_algorithms = ["MD5", "SHA1", "SHA-1", "DES", "DESede", "RC2", "RC4", "ECB"]

        script_js = r"""
// ============================================================
// Cryptographic Operation Hook Script
// ============================================================
'use strict';

function emit(tag, data) {
    console.log('[FRIDA_FINDING] ' + JSON.stringify({ tag: tag, data: data, ts: new Date().toISOString() }));
}

function bytesToHex(javaBytes) {
    try {
        if (!javaBytes) return '';
        var hex = '';
        for (var i = 0; i < Math.min(javaBytes.length, 64); i++) {
            hex += ('0' + (javaBytes[i] & 0xff).toString(16)).slice(-2);
        }
        return hex + (javaBytes.length > 64 ? '...' : '');
    } catch (e) { return ''; }
}

function isWeakAlgorithm(alg) {
    var weak = ['MD5', 'SHA1', 'SHA-1', 'DES', 'DESede', 'RC2', 'RC4', 'ECB'];
    if (!alg) return false;
    return weak.some(function (w) { return alg.toUpperCase().indexOf(w.toUpperCase()) >= 0; });
}

Java.perform(function () {

    // ── MessageDigest ────────────────────────────────────────────────────
    try {
        var MessageDigest = Java.use('java.security.MessageDigest');
        MessageDigest.getInstance.overload('java.lang.String').implementation = function (algorithm) {
            if (isWeakAlgorithm(algorithm)) {
                emit('weak_hash', { algorithm: algorithm, reason: 'Weak hash algorithm in use' });
            }
            return this.getInstance(algorithm);
        };
        MessageDigest.digest.overload('[B').implementation = function (input) {
            var alg = this.getAlgorithm();
            var result = this.digest(input);
            emit('hash_op', {
                algorithm: alg,
                input_hex: bytesToHex(input),
                output_hex: bytesToHex(result),
                weak: isWeakAlgorithm(alg)
            });
            return result;
        };
        console.log('[Crypto-Hook] MessageDigest hooked.');
    } catch (e) {
        console.log('[Crypto-Hook] MessageDigest hook failed: ' + e.message);
    }

    // ── Cipher ────────────────────────────────────────────────────────────
    try {
        var Cipher = Java.use('javax.crypto.Cipher');
        Cipher.getInstance.overload('java.lang.String').implementation = function (transformation) {
            if (isWeakAlgorithm(transformation)) {
                emit('weak_cipher', { transformation: transformation });
            }
            return this.getInstance(transformation);
        };
        Cipher.doFinal.overload('[B').implementation = function (input) {
            var alg = this.getAlgorithm();
            var result = this.doFinal(input);
            emit('cipher_op', {
                algorithm: alg,
                mode: this.getAlgorithm(),
                input_hex: bytesToHex(input),
                output_length: result ? result.length : 0,
                weak: isWeakAlgorithm(alg)
            });
            return result;
        };
        console.log('[Crypto-Hook] Cipher.doFinal hooked.');
    } catch (e) {
        console.log('[Crypto-Hook] Cipher hook failed: ' + e.message);
    }

    // ── SecretKeySpec (detect hardcoded keys) ─────────────────────────────
    try {
        var SecretKeySpec = Java.use('javax.crypto.spec.SecretKeySpec');
        SecretKeySpec.$init.overload('[B', 'java.lang.String').implementation = function (keyBytes, algorithm) {
            var keyHex = bytesToHex(keyBytes);
            // Flag if key looks static/predictable (all same bytes, or well-known test keys)
            var isHardcoded = false;
            var firstByte = keyBytes && keyBytes.length > 0 ? keyBytes[0] : -1;
            if (keyBytes && keyBytes.length > 0) {
                var allSame = true;
                for (var i = 1; i < keyBytes.length; i++) {
                    if (keyBytes[i] !== firstByte) { allSame = false; break; }
                }
                isHardcoded = allSame || keyHex === '0'.repeat(keyHex.length);
            }
            emit('secret_key_spec', {
                algorithm: algorithm,
                key_hex: keyHex,
                key_length_bits: keyBytes ? keyBytes.length * 8 : 0,
                weak_algorithm: isWeakAlgorithm(algorithm),
                possibly_hardcoded: isHardcoded
            });
            if (isHardcoded) {
                emit('hardcoded_key', { algorithm: algorithm, key_hex: keyHex });
            }
            return this.$init(keyBytes, algorithm);
        };
        console.log('[Crypto-Hook] SecretKeySpec constructor hooked.');
    } catch (e) {
        console.log('[Crypto-Hook] SecretKeySpec hook failed: ' + e.message);
    }

    // ── IvParameterSpec (detect static IVs) ──────────────────────────────
    try {
        var IvParameterSpec = Java.use('javax.crypto.spec.IvParameterSpec');
        IvParameterSpec.$init.overload('[B').implementation = function (iv) {
            var ivHex = bytesToHex(iv);
            var allZero = ivHex.replace(/0/g, '').length === 0;
            emit('iv_spec', {
                iv_hex: ivHex,
                iv_length: iv ? iv.length : 0,
                static_iv: allZero
            });
            if (allZero) {
                emit('static_iv', { iv_hex: ivHex, risk: 'All-zero IV is predictable and breaks semantic security' });
            }
            return this.$init(iv);
        };
        console.log('[Crypto-Hook] IvParameterSpec hooked.');
    } catch (e) {
        console.log('[Crypto-Hook] IvParameterSpec hook failed: ' + e.message);
    }

    // ── Mac (HMAC) ────────────────────────────────────────────────────────
    try {
        var Mac = Java.use('javax.crypto.Mac');
        Mac.getInstance.overload('java.lang.String').implementation = function (algorithm) {
            emit('mac_init', { algorithm: algorithm, weak: isWeakAlgorithm(algorithm) });
            return this.getInstance(algorithm);
        };
        Mac.doFinal.overload('[B').implementation = function (input) {
            var result = this.doFinal(input);
            emit('mac_op', {
                algorithm: this.getAlgorithm(),
                input_hex: bytesToHex(input),
                output_hex: bytesToHex(result)
            });
            return result;
        };
        console.log('[Crypto-Hook] Mac hooked.');
    } catch (e) {
        console.log('[Crypto-Hook] Mac hook failed: ' + e.message);
    }

    console.log('[Crypto-Hook] All cryptographic hooks installed.');
});
"""
        return FridaScript(
            name="crypto_hooks",
            description="Hook MessageDigest, Cipher, SecretKeySpec, IvParameterSpec, and Mac to detect weak crypto and hardcoded keys",
            targets=targets,
            script_content=self._build_js_header() + script_js,
            platform="android",
            auto_run=False,
        )

    # ── Network Hook ──────────────────────────────────────────────────────────

    def generate_network_hook_script(self, network_classes: List[str]) -> FridaScript:
        """
        Hook OkHttp3, Retrofit, and HttpURLConnection to log requests/responses
        and detect authentication tokens, API keys, and sensitive data in traffic.
        """
        targets = [
            HookTarget("okhttp3.OkHttpClient", "newCall", "network", 9, "Intercept OkHttp3 calls"),
            HookTarget("java.net.HttpURLConnection", "connect", "network", 7, "Intercept HttpURLConnection"),
        ]

        script_js = r"""
// ============================================================
// Network Traffic Hook Script
// ============================================================
'use strict';

function emit(tag, data) {
    console.log('[FRIDA_FINDING] ' + JSON.stringify({ tag: tag, data: data, ts: new Date().toISOString() }));
}

function truncate(s, n) {
    if (!s) return '';
    s = String(s);
    return s.length > n ? s.substring(0, n) + '...' : s;
}

function isSensitiveHeader(name) {
    var sensitive = ['authorization', 'x-api-key', 'x-auth-token', 'cookie', 'token', 'x-access-token', 'api-key'];
    return sensitive.indexOf(name.toLowerCase()) >= 0;
}

Java.perform(function () {

    // ── OkHttp3 Request Builder ───────────────────────────────────────────
    try {
        var Request = Java.use('okhttp3.Request');
        var RequestBuilder = Java.use('okhttp3.Request$Builder');

        RequestBuilder.build.implementation = function () {
            var req = this.build();
            try {
                var url = req.url().toString();
                var method = req.method();
                var headers = {};
                var headerNames = req.headers().names().toArray();
                for (var i = 0; i < headerNames.length; i++) {
                    var hName = String(headerNames[i]);
                    var hVal = req.header(hName);
                    headers[hName] = isSensitiveHeader(hName) ?
                        truncate(hVal, 30) + ' [SENSITIVE]' :
                        truncate(hVal, 100);
                    if (isSensitiveHeader(hName)) {
                        emit('auth_header_found', { header: hName, value: truncate(hVal, 60), url: url });
                    }
                }
                var bodyStr = '';
                try {
                    var body = req.body();
                    if (body) {
                        var buffer = Java.use('okio.Buffer').$new();
                        body.writeTo(buffer);
                        bodyStr = buffer.readUtf8();
                    }
                } catch (be) { bodyStr = '[body read error]'; }
                emit('network_request', { url: url, method: method, headers: headers, body: truncate(bodyStr, 500) });
            } catch (ie) {
                emit('network_request_error', { error: ie.message });
            }
            return req;
        };
        console.log('[Network-Hook] OkHttp3 Request.Builder.build() hooked.');
    } catch (e) {
        console.log('[Network-Hook] OkHttp3 Request hook failed: ' + e.message);
    }

    // ── OkHttp3 Response ─────────────────────────────────────────────────
    try {
        var RealCall = Java.use('okhttp3.internal.connection.RealCall');
        RealCall.execute.implementation = function () {
            var response = this.execute();
            try {
                var code = response.code();
                var url = response.request().url().toString();
                var bodyStr = '';
                try {
                    var rb = response.peekBody(4096);
                    if (rb) bodyStr = rb.string();
                } catch (be) { }
                emit('network_response', { url: url, status: code, body: truncate(bodyStr, 500) });
            } catch (re) { }
            return response;
        };
        console.log('[Network-Hook] OkHttp3 RealCall.execute() hooked.');
    } catch (e) {
        console.log('[Network-Hook] OkHttp3 RealCall hook failed: ' + e.message);
    }

    // ── HttpURLConnection ─────────────────────────────────────────────────
    try {
        var HttpURLConnection = Java.use('java.net.HttpURLConnection');
        HttpURLConnection.setRequestProperty.implementation = function (key, value) {
            if (isSensitiveHeader(key)) {
                emit('auth_header_found', { header: key, value: truncate(value, 60), source: 'HttpURLConnection' });
            }
            return this.setRequestProperty(key, value);
        };
        HttpURLConnection.connect.implementation = function () {
            try {
                emit('network_connect', { url: this.getURL().toString(), method: this.getRequestMethod() });
            } catch (e) { }
            return this.connect();
        };
        console.log('[Network-Hook] HttpURLConnection hooked.');
    } catch (e) {
        console.log('[Network-Hook] HttpURLConnection hook failed: ' + e.message);
    }

    // ── URL.openConnection ────────────────────────────────────────────────
    try {
        var URL = Java.use('java.net.URL');
        URL.openConnection.overload().implementation = function () {
            emit('url_open', { url: this.toString() });
            return this.openConnection();
        };
        console.log('[Network-Hook] URL.openConnection() hooked.');
    } catch (e) {
        console.log('[Network-Hook] URL.openConnection hook failed: ' + e.message);
    }

    console.log('[Network-Hook] All network hooks installed.');
});
"""
        return FridaScript(
            name="network_hooks",
            description="Hook OkHttp3, HttpURLConnection, and URL to log all network requests/responses and detect auth headers",
            targets=targets,
            script_content=self._build_js_header() + script_js,
            platform="android",
            auto_run=False,
        )

    # ── Storage Hook ──────────────────────────────────────────────────────────

    def generate_storage_hook_script(self) -> FridaScript:
        """
        Hook SharedPreferences, FileOutputStream, and SQLiteDatabase to detect
        sensitive data written to persistent storage.
        """
        targets = [
            HookTarget("android.content.SharedPreferences$Editor", "putString", "storage", 9,
                       "Detect credentials stored in SharedPreferences"),
            HookTarget("java.io.FileOutputStream", "write", "storage", 7,
                       "Monitor file writes"),
            HookTarget("android.database.sqlite.SQLiteDatabase", "execSQL", "storage", 8,
                       "Monitor raw SQL execution"),
        ]

        script_js = r"""
// ============================================================
// Storage Hook Script — SharedPreferences, Files, SQLite
// ============================================================
'use strict';

function emit(tag, data) {
    console.log('[FRIDA_FINDING] ' + JSON.stringify({ tag: tag, data: data, ts: new Date().toISOString() }));
}

var SENSITIVE_KEYS = ['password', 'passwd', 'pwd', 'token', 'secret', 'key', 'apikey',
                      'api_key', 'credential', 'auth', 'session', 'private', 'pin'];

function isSensitiveKey(k) {
    if (!k) return false;
    var lower = String(k).toLowerCase();
    return SENSITIVE_KEYS.some(function (sk) { return lower.indexOf(sk) >= 0; });
}

Java.perform(function () {

    // ── SharedPreferences.Editor ──────────────────────────────────────────
    try {
        var SharedPrefsEditor = Java.use('android.content.SharedPreferences$Editor');
        SharedPrefsEditor.putString.implementation = function (key, value) {
            if (isSensitiveKey(key)) {
                emit('sensitive_prefs_write', {
                    key: key,
                    value_preview: value ? String(value).substring(0, 40) : null,
                    risk: 'Sensitive value stored in SharedPreferences (unencrypted)'
                });
            }
            return this.putString(key, value);
        };
        SharedPrefsEditor.putInt.implementation = function (key, value) {
            if (isSensitiveKey(key)) {
                emit('sensitive_prefs_write', { key: key, value: value, type: 'int' });
            }
            return this.putInt(key, value);
        };
        SharedPrefsEditor.putBoolean.implementation = function (key, value) {
            if (isSensitiveKey(key)) {
                emit('sensitive_prefs_write', { key: key, value: value, type: 'bool' });
            }
            return this.putBoolean(key, value);
        };
        console.log('[Storage-Hook] SharedPreferences.Editor hooked.');
    } catch (e) {
        console.log('[Storage-Hook] SharedPreferences hook failed: ' + e.message);
    }

    // ── SharedPreferences.getString (read) ────────────────────────────────
    try {
        var SharedPreferences = Java.use('android.content.SharedPreferences');
        // Note: SharedPreferences is an interface; hook concrete impl
        var SharedPreferencesImpl = Java.use('android.app.SharedPreferencesImpl');
        SharedPreferencesImpl.getString.implementation = function (key, defValue) {
            var result = this.getString(key, defValue);
            if (isSensitiveKey(key) && result) {
                emit('sensitive_prefs_read', { key: key, value_preview: String(result).substring(0, 40) });
            }
            return result;
        };
    } catch (e) { /* SharedPreferencesImpl may not be accessible on all Android versions */ }

    // ── FileOutputStream ─────────────────────────────────────────────────
    try {
        var FileOutputStream = Java.use('java.io.FileOutputStream');
        FileOutputStream.$init.overload('java.lang.String').implementation = function (path) {
            if (isSensitiveKey(path)) {
                emit('sensitive_file_open', { path: path, mode: 'write' });
            }
            emit('file_open', { path: path });
            return this.$init(path);
        };
        FileOutputStream.$init.overload('java.io.File').implementation = function (file) {
            var path = file ? file.getAbsolutePath() : '';
            emit('file_open', { path: path });
            return this.$init(file);
        };
        console.log('[Storage-Hook] FileOutputStream hooked.');
    } catch (e) {
        console.log('[Storage-Hook] FileOutputStream hook failed: ' + e.message);
    }

    // ── SQLiteDatabase ────────────────────────────────────────────────────
    try {
        var SQLiteDatabase = Java.use('android.database.sqlite.SQLiteDatabase');
        SQLiteDatabase.execSQL.overload('java.lang.String').implementation = function (sql) {
            emit('sqlite_exec', { sql: String(sql).substring(0, 300) });
            return this.execSQL(sql);
        };
        SQLiteDatabase.rawQuery.overload('java.lang.String', '[Ljava.lang.String;').implementation = function (sql, args) {
            emit('sqlite_query', { sql: String(sql).substring(0, 300), args: args ? String(args) : null });
            return this.rawQuery(sql, args);
        };
        console.log('[Storage-Hook] SQLiteDatabase hooked.');
    } catch (e) {
        console.log('[Storage-Hook] SQLiteDatabase hook failed: ' + e.message);
    }

    // ── Android Keystore (read) ───────────────────────────────────────────
    try {
        var KeyStore = Java.use('java.security.KeyStore');
        KeyStore.getEntry.overload('java.lang.String', 'java.security.KeyStore$ProtectionParameter').implementation = function (alias, param) {
            emit('keystore_access', { alias: alias, operation: 'getEntry' });
            return this.getEntry(alias, param);
        };
        console.log('[Storage-Hook] KeyStore.getEntry hooked.');
    } catch (e) { }

    console.log('[Storage-Hook] All storage hooks installed.');
});
"""
        return FridaScript(
            name="storage_hooks",
            description="Hook SharedPreferences, FileOutputStream, and SQLiteDatabase to detect sensitive data in storage",
            targets=targets,
            script_content=self._build_js_header() + script_js,
            platform="android",
            auto_run=False,
        )

    # ── Anti-Debug Bypass ─────────────────────────────────────────────────────

    def generate_anti_debug_bypass(self) -> FridaScript:
        """
        Bypass debugger detection, ptrace anti-debug, and device fingerprinting.
        """
        targets = [
            HookTarget("android.os.Debug", "isDebuggerConnected", "custom", 8,
                       "Bypass isDebuggerConnected check"),
        ]

        script_js = r"""
// ============================================================
// Anti-Debug Detection Bypass
// ============================================================
'use strict';

function emit(tag, data) {
    console.log('[FRIDA_FINDING] ' + JSON.stringify({ tag: tag, data: data }));
}

Java.perform(function () {

    // ── Debug.isDebuggerConnected ─────────────────────────────────────────
    try {
        var Debug = Java.use('android.os.Debug');
        Debug.isDebuggerConnected.implementation = function () {
            emit('anti_debug_bypass', { method: 'Debug.isDebuggerConnected', returning: false });
            return false;
        };
        Debug.waitingForDebugger.implementation = function () {
            emit('anti_debug_bypass', { method: 'Debug.waitingForDebugger', returning: false });
            return false;
        };
        console.log('[Anti-Debug] Debug.isDebuggerConnected hooked.');
    } catch (e) {
        console.log('[Anti-Debug] Debug hook failed: ' + e.message);
    }

    // ── ApplicationInfo.FLAG_DEBUGGABLE ───────────────────────────────────
    try {
        var ApplicationInfo = Java.use('android.content.pm.ApplicationInfo');
        ApplicationInfo.flags.value = ApplicationInfo.flags.value & ~(1 << 1);  // clear FLAG_DEBUGGABLE
        console.log('[Anti-Debug] ApplicationInfo.FLAG_DEBUGGABLE cleared.');
    } catch (e) { }

    // ── Secure.getString(ANDROID_ID) device fingerprint ───────────────────
    try {
        var Secure = Java.use('android.provider.Settings$Secure');
        Secure.getString.overload('android.content.ContentResolver', 'java.lang.String').implementation = function (cr, name) {
            var result = this.getString(cr, name);
            if (name === 'android_id') {
                emit('device_fingerprint', { field: 'ANDROID_ID', value: result,
                    risk: 'App reads ANDROID_ID for device fingerprinting/anti-tamper' });
            }
            return result;
        };
        console.log('[Anti-Debug] Settings.Secure.getString hooked for ANDROID_ID.');
    } catch (e) {
        console.log('[Anti-Debug] Settings.Secure hook failed: ' + e.message);
    }

    // ── PackageManager signature check (common integrity pattern) ─────────
    try {
        var PackageInfo = Java.use('android.content.pm.PackageInfo');
        var PackageManager = Java.use('android.content.pm.PackageManager');
        PackageManager.getPackageInfo.overload('java.lang.String', 'int').implementation = function (packageName, flags) {
            var result = this.getPackageInfo(packageName, flags);
            // Flag 64 = GET_SIGNATURES
            if ((flags & 64) !== 0) {
                emit('signature_check', { package: packageName,
                    risk: 'App performing signature verification (tamper detection)' });
            }
            return result;
        };
        console.log('[Anti-Debug] PackageManager.getPackageInfo signature check hooked.');
    } catch (e) { }

    // ── Native ptrace self-check (best-effort) ────────────────────────────
    try {
        var ptrace_ptr = Module.findExportByName(null, 'ptrace');
        if (ptrace_ptr) {
            Interceptor.attach(ptrace_ptr, {
                onEnter: function (args) {
                    // PTRACE_TRACEME = 0
                    if (args[0].toInt32() === 0) {
                        emit('ptrace_self', { request: 'PTRACE_TRACEME' });
                    }
                }
            });
            console.log('[Anti-Debug] ptrace() hooked.');
        }
    } catch (e) { }

    console.log('[Anti-Debug] All anti-debug bypasses installed.');
});
"""
        return FridaScript(
            name="anti_debug_bypass",
            description="Bypass debugger detection, ptrace anti-debug, and device fingerprinting",
            targets=targets,
            script_content=self._build_js_header() + script_js,
            platform="android",
            auto_run=True,
        )

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _build_js_header(self) -> str:
        """Standard Frida script boilerplate and error handling."""
        return """// Auto-generated by FridaScriptGenerator
// Usage: frida -U -f <package_name> -l <script.js> --no-pause
//        frida -U --attach-name <package_name> -l <script.js>

'use strict';

if (typeof Java === 'undefined') {
    console.error('[ERROR] Java bridge not available. Is this an Android process?');
} else {
    console.log('[Frida] Script loaded. Java.available=' + Java.available);
}

// Global error handler
Process.setExceptionHandler(function (ex) {
    console.error('[Frida-Exception] ' + ex.type + ' at ' + ex.address + ': ' + ex.toString());
    return false;  // don't swallow the exception
});

"""

    def _build_hook_template(
        self,
        class_name: str,
        method_name: str,
        log_args: bool = True,
        log_return: bool = True,
    ) -> str:
        """
        Generate a generic JS hook template for a given class.method.
        Uses Frida's Java.use() / implementation override pattern.
        """
        safe_var = class_name.replace(".", "_").replace("$", "_") + "_" + method_name
        args_log = "emit('hook', { class: '" + class_name + "', method: '" + method_name + "', args: Array.from(arguments).map(String) });" if log_args else ""
        return_log = "emit('hook_return', { class: '" + class_name + "', method: '" + method_name + "', result: String(ret) });" if log_return else ""

        return f"""    // Hook: {class_name}.{method_name}
    try {{
        var {safe_var}_cls = Java.use('{class_name}');
        {safe_var}_cls['{method_name}'].implementation = function () {{
            {args_log}
            var ret = this['{method_name}'].apply(this, arguments);
            {return_log}
            return ret;
        }};
        console.log('[Hook] {class_name}.{method_name} installed.');
    }} catch (e) {{
        console.log('[Hook] Failed: {class_name}.{method_name} — ' + e.message);
    }}
"""

    def save_scripts(self, scripts: List[FridaScript], output_dir: str) -> List[str]:
        """
        Save each FridaScript to a .js file in output_dir.
        Returns a list of absolute file paths.
        """
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        saved: List[str] = []
        for script in scripts:
            filename = f"frida_{script.name}_{script.platform}.js"
            fpath = out_path / filename
            try:
                fpath.write_text(script.script_content, encoding="utf-8")
                log.info("Saved Frida script: %s", fpath)
                saved.append(str(fpath.resolve()))
            except Exception as exc:
                log.warning("Failed to save script %s: %s", filename, exc)

        return saved


# ─────────────────────────────────────────────────────────────────────────────
#  Module singleton
# ─────────────────────────────────────────────────────────────────────────────

frida_script_generator = FridaScriptGenerator()
