import datetime
import json
import html
from typing import Dict, Any

class StandardizedForensicReport:
    """
    Standardized Forensic Report generator for Aegis Mobile Forensic Suite.
    """

    def generate_html(self, report_data: Dict[str, Any]) -> str:
        """
        Generate a standardized HTML forensic report.
        """
        app_info = report_data.get("app", {})
        results = report_data.get("result", {})
        
        # Extract specific data points
        static_analysis = results.get("static_analysis", {})
        dynamic_analysis = results.get("dynamic_analysis", {})
        secrets = results.get("secrets", [])
        vulnerabilities = results.get("all_vulnerabilities", [])
        
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Sanitize basic info
        app_name = html.escape(str(app_info.get("name", "Unknown App")))
        package_name = html.escape(str(app_info.get("package_name", "N/A")))
        version = html.escape(str(app_info.get("version", "N/A")))
        target_sdk = html.escape(str(static_analysis.get("target_sdk", "N/A")))
        
        # Simple HTML template
        html_template = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aegis Mobile Forensic Report - {app_name}</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 1200px; margin: 0 auto; padding: 20px; background-color: #f4f7f6; }}
        header {{ background-color: #2c3e50; color: white; padding: 20px; border-radius: 8px 8px 0 0; margin-bottom: 20px; }}
        h1, h2, h3 {{ color: #2c3e50; }}
        .summary {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); margin-bottom: 20px; }}
        .section {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); margin-bottom: 20px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
        th, td {{ text-align: left; padding: 12px; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #ecf0f1; }}
        .severity-high {{ color: #e74c3c; font-weight: bold; }}
        .severity-medium {{ color: #f39c12; font-weight: bold; }}
        .severity-low {{ color: #3498db; font-weight: bold; }}
        pre {{ background: #f8f9fa; padding: 10px; border: 1px solid #ddd; border-radius: 4px; overflow-x: auto; }}
        .footer {{ text-align: center; font-size: 0.8em; color: #7f8c8d; margin-top: 40px; }}
    </style>
</head>
<body>
    <header>
        <h1>Aegis Mobile Forensic Report</h1>
        <p>Application: <strong>{app_name}</strong> ({package_name})</p>
        <p>Generated: {timestamp}</p>
    </header>

    <div class="summary">
        <h2>Executive Summary</h2>
        <p>Comprehensive security assessment of the mobile application <strong>{app_name}</strong>.</p>
        <table>
            <tr><th>Attribute</th><th>Value</th></tr>
            <tr><td>Package Name</td><td>{package_name}</td></tr>
            <tr><td>Version</td><td>{version}</td></tr>
            <tr><td>Target SDK</td><td>{target_sdk}</td></tr>
            <tr><td>Total Vulnerabilities</td><td>{total_vulns}</td></tr>
        </table>
    </div>

    <div class="section">
        <h2>Static Analysis Findings</h2>
        <p>Automated static analysis of the binary artifacts.</p>
        {static_content}
    </div>

    <div class="section">
        <h2>Secrets Discovery</h2>
        <p>Sensitive information found in the application package.</p>
        {secrets_content}
    </div>

    <div class="section">
        <h2>Security Vulnerabilities</h2>
        <table>
            <tr><th>ID</th><th>Title</th><th>Severity</th><th>Description</th></tr>
            {vulns_content}
        </table>
    </div>

    <div class="footer">
        <p>Generated by Aegis Mobile Forensic Suite - OneInfinity Security</p>
    </div>
</body>
</html>
        """
        
        # Helper to generate rows
        vulns_content = ""
        for v in vulnerabilities:
            sev = v.get('severity', 'low').lower()
            if sev not in ['high', 'medium', 'low']:
                sev_class = "severity-low"
            else:
                sev_class = f"severity-{sev}"
            
            v_id = html.escape(str(v.get('id', 'N/A')))
            v_title = html.escape(str(v.get('title', 'N/A')))
            v_severity = html.escape(str(v.get('severity', 'LOW')))
            v_description = html.escape(str(v.get('description', 'No description')))
                
            vulns_content += f"<tr><td>{v_id}</td><td>{v_title}</td><td class='{sev_class}'>{v_severity}</td><td>{v_description}</td></tr>"
        
        if not vulnerabilities:
            vulns_content = "<tr><td colspan='4'>No vulnerabilities identified.</td></tr>"

        secrets_content = "<ul>"
        for s in secrets:
            s_type = html.escape(str(s.get('type', 'Secret')))
            s_value = html.escape(str(s.get('value', 'REDACTED')))
            s_file = html.escape(str(s.get('file', 'Unknown')))
            secrets_content += f"<li><strong>{s_type}:</strong> <code>{s_value}</code> (Location: {s_file})</li>"
        secrets_content += "</ul>"
        if not secrets:
            secrets_content = "<p>No secrets identified.</p>"

        permissions = static_analysis.get('permissions', [])
        escaped_permissions = [html.escape(str(p)) for p in permissions]
        
        static_content = f"""
        <p><strong>Min SDK:</strong> {html.escape(str(static_analysis.get('min_sdk', 'N/A')))}</p>
        <p><strong>Target SDK:</strong> {target_sdk}</p>
        <p><strong>Permissions:</strong> {', '.join(escaped_permissions) if escaped_permissions else 'None'}</p>
        """

        return html_template.format(
            app_name=app_name,
            package_name=package_name,
            version=version,
            target_sdk=target_sdk,
            total_vulns=len(vulnerabilities),
            timestamp=timestamp,
            static_content=static_content,
            secrets_content=secrets_content,
            vulns_content=vulns_content
        )

