"""foundry_poc_generator.py — Foundry test PoC template generator for smart contract vulns."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class FoundryPoC:
    finding_title: str
    contract_name: str
    vuln_type: str
    test_code: str
    setup_code: str = ""
    description: str = ""

    def full_test_file(self) -> str:
        return f"""// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// PoC for: {self.finding_title}
// Vuln type: {self.vuln_type}
// Generated by OneInfinity

contract {self.contract_name}Exploit is Test {{
    {self.contract_name} target;

    function setUp() public {{
        {self.setup_code or f'target = new {self.contract_name}();'}
    }}

    function test_exploit() public {{
        {self.test_code}
    }}
}}
"""


_TEMPLATES: dict[str, dict] = {
    "reentrancy": {
        "setup": """
        // Fund the target with 10 ETH
        vm.deal(address(target), 10 ether);
        vm.deal(address(this), 1 ether);""",
        "test": """
        uint256 balanceBefore = address(this).balance;
        // Trigger reentrancy via deposit + malicious fallback
        target.deposit{value: 1 ether}();
        target.withdraw();
        uint256 profit = address(this).balance - balanceBefore;
        assertGt(profit, 1 ether, "Reentrancy drain failed");
        console.log("Drained:", profit / 1e18, "ETH");""",
        "description": "Demonstrates reentrancy drain via recursive withdraw calls.",
    },
    "integer_overflow": {
        "setup": "// Deploy target contract",
        "test": """
        uint256 maxUint = type(uint256).max;
        // Overflow: maxUint + 1 wraps to 0
        uint256 overflow = target.add(maxUint, 1);
        assertEq(overflow, 0, "Integer overflow not triggered");
        console.log("Overflow result:", overflow);""",
        "description": "Demonstrates integer overflow causing accounting desync.",
    },
    "access_control": {
        "setup": "address attacker = makeAddr(\"attacker\");",
        "test": """
        address attacker = makeAddr("attacker");
        vm.startPrank(attacker);
        // Unauthorized call to privileged function
        target.adminFunction();
        vm.stopPrank();
        // If we reach here, access control is missing
        assertTrue(true, "Access control bypass succeeded");""",
        "description": "Demonstrates missing access control on privileged function.",
    },
    "oracle_manipulation": {
        "setup": """
        // Fork mainnet at a specific block for flash loan simulation
        // vm.createSelectFork(vm.rpcUrl("mainnet"));""",
        "test": """
        // Simulate flash loan to manipulate oracle price
        uint256 loanAmount = 1_000_000e18;
        // 1. Borrow large amount
        // 2. Manipulate pool reserves (skew price)
        // 3. Call target.getPrice() — reads manipulated oracle
        // 4. Repay flash loan
        // 5. Profit from the price discrepancy
        uint256 priceManipulated = target.getPrice();
        console.log("Manipulated price:", priceManipulated);
        // Assert price is far from fair value
        assertTrue(priceManipulated > 0, "Oracle manipulation vector exists");""",
        "description": "Demonstrates flash-loan-based oracle price manipulation.",
    },
    "signature_replay": {
        "setup": "// Record a valid signature",
        "test": """
        // Capture a valid signature
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(1, keccak256("operation_hash"));
        bytes memory sig = abi.encodePacked(r, s, v);
        // First use — should succeed
        target.executeWithSig(sig);
        // Replay — should fail if replay protection exists
        vm.expectRevert();
        target.executeWithSig(sig);  // This should revert; if it doesn't, replay is possible""",
        "description": "Demonstrates signature replay attack due to missing nonce protection.",
    },
    "tx_origin": {
        "setup": "address victim = makeAddr(\"victim\");",
        "test": """
        address victim = makeAddr("victim");
        // Phishing: victim calls attacker contract which calls target
        // target checks tx.origin == owner (victim) instead of msg.sender
        vm.prank(victim, victim);  // sets both msg.sender and tx.origin
        // Simulates victim interacting with malicious contract
        target.privilegedAction();
        console.log("tx.origin bypass succeeded");""",
        "description": "Demonstrates tx.origin-based authorization bypass.",
    },
    "unchecked_return": {
        "setup": "",
        "test": """
        // Call that returns false on failure but return value is not checked
        bool success = target.transfer(address(0xdead), 1000e18);
        // If success is false but no revert occurred, the contract silently fails
        console.log("Transfer return value:", success);
        // Demonstrate that state changed despite 'failure'
        assertEq(target.balanceOf(address(0xdead)), 1000e18, "Silent failure: state changed");""",
        "description": "Demonstrates unchecked low-level call return value allowing silent failures.",
    },
    "default": {
        "setup": "// Add setup code specific to the vulnerability",
        "test": """
        // Add exploit steps here
        // 1. Set up initial state
        // 2. Trigger the vulnerability
        // 3. Assert exploit impact
        assertTrue(true, "Vulnerability triggered");""",
        "description": "Generic PoC template — customize for the specific vulnerability.",
    },
}


def generate(
    vuln_type: str,
    contract_name: str,
    finding_title: str,
    contract_address: str = "",
) -> FoundryPoC:
    """Generate a Foundry PoC for the given vulnerability type."""
    key = vuln_type.lower().replace("-", "_").replace(" ", "_")
    tmpl = _TEMPLATES.get(key, _TEMPLATES["default"])

    # Replace contract name in setup if needed
    setup = tmpl["setup"]
    if "{contract_name}" in setup:
        setup = setup.replace("{contract_name}", contract_name)
    if contract_address:
        setup = f"target = {contract_name}({contract_address});\n        {setup}"

    return FoundryPoC(
        finding_title=finding_title,
        contract_name=contract_name,
        vuln_type=vuln_type,
        test_code=tmpl["test"],
        setup_code=setup,
        description=tmpl.get("description", ""),
    )
