// Auto-generated by FridaScriptGenerator
// Usage: frida -U -f <package_name> -l <script.js> --no-pause
//        frida -U --attach-name <package_name> -l <script.js>

'use strict';

if (typeof Java === 'undefined') {
    console.error('[ERROR] Java bridge not available. Is this an Android process?');
} else {
    console.log('[Frida] Script loaded. Java.available=' + Java.available);
}

// Global error handler
Process.setExceptionHandler(function (ex) {
    console.error('[Frida-Exception] ' + ex.type + ' at ' + ex.address + ': ' + ex.toString());
    return false;  // don't swallow the exception
});


// ============================================================
// Anti-Debug Detection Bypass
// ============================================================
'use strict';

function emit(tag, data) {
    console.log('[FRIDA_FINDING] ' + JSON.stringify({ tag: tag, data: data }));
}

Java.perform(function () {

    // ── Debug.isDebuggerConnected ─────────────────────────────────────────
    try {
        var Debug = Java.use('android.os.Debug');
        Debug.isDebuggerConnected.implementation = function () {
            emit('anti_debug_bypass', { method: 'Debug.isDebuggerConnected', returning: false });
            return false;
        };
        Debug.waitingForDebugger.implementation = function () {
            emit('anti_debug_bypass', { method: 'Debug.waitingForDebugger', returning: false });
            return false;
        };
        console.log('[Anti-Debug] Debug.isDebuggerConnected hooked.');
    } catch (e) {
        console.log('[Anti-Debug] Debug hook failed: ' + e.message);
    }

    // ── ApplicationInfo.FLAG_DEBUGGABLE ───────────────────────────────────
    try {
        var ApplicationInfo = Java.use('android.content.pm.ApplicationInfo');
        ApplicationInfo.flags.value = ApplicationInfo.flags.value & ~(1 << 1);  // clear FLAG_DEBUGGABLE
        console.log('[Anti-Debug] ApplicationInfo.FLAG_DEBUGGABLE cleared.');
    } catch (e) { }

    // ── Secure.getString(ANDROID_ID) device fingerprint ───────────────────
    try {
        var Secure = Java.use('android.provider.Settings$Secure');
        Secure.getString.overload('android.content.ContentResolver', 'java.lang.String').implementation = function (cr, name) {
            var result = this.getString(cr, name);
            if (name === 'android_id') {
                emit('device_fingerprint', { field: 'ANDROID_ID', value: result,
                    risk: 'App reads ANDROID_ID for device fingerprinting/anti-tamper' });
            }
            return result;
        };
        console.log('[Anti-Debug] Settings.Secure.getString hooked for ANDROID_ID.');
    } catch (e) {
        console.log('[Anti-Debug] Settings.Secure hook failed: ' + e.message);
    }

    // ── PackageManager signature check (common integrity pattern) ─────────
    try {
        var PackageInfo = Java.use('android.content.pm.PackageInfo');
        var PackageManager = Java.use('android.content.pm.PackageManager');
        PackageManager.getPackageInfo.overload('java.lang.String', 'int').implementation = function (packageName, flags) {
            var result = this.getPackageInfo(packageName, flags);
            // Flag 64 = GET_SIGNATURES
            if ((flags & 64) !== 0) {
                emit('signature_check', { package: packageName,
                    risk: 'App performing signature verification (tamper detection)' });
            }
            return result;
        };
        console.log('[Anti-Debug] PackageManager.getPackageInfo signature check hooked.');
    } catch (e) { }

    // ── Native ptrace self-check (best-effort) ────────────────────────────
    try {
        var ptrace_ptr = Module.findExportByName(null, 'ptrace');
        if (ptrace_ptr) {
            Interceptor.attach(ptrace_ptr, {
                onEnter: function (args) {
                    // PTRACE_TRACEME = 0
                    if (args[0].toInt32() === 0) {
                        emit('ptrace_self', { request: 'PTRACE_TRACEME' });
                    }
                }
            });
            console.log('[Anti-Debug] ptrace() hooked.');
        }
    } catch (e) { }

    console.log('[Anti-Debug] All anti-debug bypasses installed.');
});
