// Auto-generated by FridaScriptGenerator
// Usage: frida -U -f <package_name> -l <script.js> --no-pause
//        frida -U --attach-name <package_name> -l <script.js>

'use strict';

if (typeof Java === 'undefined') {
    console.error('[ERROR] Java bridge not available. Is this an Android process?');
} else {
    console.log('[Frida] Script loaded. Java.available=' + Java.available);
}

// Global error handler
Process.setExceptionHandler(function (ex) {
    console.error('[Frida-Exception] ' + ex.type + ' at ' + ex.address + ': ' + ex.toString());
    return false;  // don't swallow the exception
});


// ============================================================
// Root / Jailbreak Detection Bypass
// ============================================================
'use strict';

function emit(tag, data) {
    console.log('[FRIDA_FINDING] ' + JSON.stringify({ tag: tag, data: data }));
}

Java.perform(function () {

    // ── 1. RootBeer ──────────────────────────────────────────────────────
    try {
        var RootBeer = Java.use('com.scottyab.rootbeer.RootBeer');
        var rootMethods = ['isRooted', 'isRootedWithoutBusyBox', 'detectRootManagementApps',
                           'detectPotentiallyDangerousApps', 'checkForSuBinary',
                           'checkSuExists', 'checkForRWPaths', 'checkDangerousProps',
                           'checkRootThroughNativeCode'];
        rootMethods.forEach(function (method) {
            try {
                RootBeer[method].implementation = function () {
                    emit('root_bypass', { library: 'RootBeer', method: method });
                    return false;
                };
            } catch (e) { }
        });
        console.log('[Root-Bypass] RootBeer hooked.');
    } catch (e) {
        console.log('[Root-Bypass] RootBeer not found: ' + e.message);
    }

    // ── 2. Build.TAGS ────────────────────────────────────────────────────
    try {
        var Build = Java.use('android.os.Build');
        Object.defineProperty(Build, 'TAGS', {
            get: function () { return 'release-keys'; }
        });
        console.log('[Root-Bypass] Build.TAGS patched to release-keys.');
    } catch (e) {
        console.log('[Root-Bypass] Build.TAGS patch failed: ' + e.message);
    }

    // ── 3. File existence checks (su, busybox) ────────────────────────────
    try {
        var File = Java.use('java.io.File');
        var SU_PATHS = [
            '/system/app/Superuser.apk', '/system/xbin/su', '/system/bin/su',
            '/sbin/su', '/su/bin/su', '/data/local/xbin/su', '/data/local/bin/su',
            '/data/local/su', '/system/sd/xbin/su', '/system/bin/failsafe/su',
            '/system/app/SuperSU.apk', '/system/app/Magisk.apk'
        ];
        File.exists.implementation = function () {
            var path = this.getAbsolutePath();
            if (SU_PATHS.indexOf(path) >= 0) {
                emit('root_bypass', { method: 'File.exists', path: path });
                return false;
            }
            return this.exists();
        };
        console.log('[Root-Bypass] File.exists() patched for su paths.');
    } catch (e) {
        console.log('[Root-Bypass] File.exists hook failed: ' + e.message);
    }

    // ── 4. Runtime.exec("su") ────────────────────────────────────────────
    try {
        var Runtime = Java.use('java.lang.Runtime');
        Runtime.exec.overload('java.lang.String').implementation = function (cmd) {
            if (cmd && cmd.indexOf('su') >= 0) {
                emit('root_bypass', { method: 'Runtime.exec', cmd: cmd });
                var IOException = Java.use('java.io.IOException');
                throw IOException.$new('Permission denied (root bypass)');
            }
            return this.exec(cmd);
        };
        Runtime.exec.overload('[Ljava.lang.String;').implementation = function (cmdArray) {
            if (cmdArray && cmdArray.length > 0 && cmdArray[0].indexOf('su') >= 0) {
                emit('root_bypass', { method: 'Runtime.exec[]', cmd: cmdArray[0] });
                var IOException = Java.use('java.io.IOException');
                throw IOException.$new('Permission denied (root bypass)');
            }
            return this.exec(cmdArray);
        };
        console.log('[Root-Bypass] Runtime.exec hooked for su commands.');
    } catch (e) {
        console.log('[Root-Bypass] Runtime.exec hook failed: ' + e.message);
    }

    // ── 5. SafetyNet / Play Integrity ─────────────────────────────────────
    try {
        var SafetyNetClient = Java.use('com.google.android.gms.safetynet.SafetyNetClient');
        SafetyNetClient.attest.implementation = function (nonce, apiKey) {
            emit('root_bypass', { method: 'SafetyNet.attest bypassed' });
            // Return a task-like stub; real bypass requires spoofing the JWS response
            return this.attest(nonce, apiKey);
        };
    } catch (e) { }

    // ── 6. SystemProperties checks ────────────────────────────────────────
    try {
        var SystemProperties = Java.use('android.os.SystemProperties');
        SystemProperties.get.overload('java.lang.String').implementation = function (key) {
            var val = this.get(key);
            if (key === 'ro.debuggable' || key === 'ro.secure') {
                emit('root_bypass', { method: 'SystemProperties.get', key: key, original: val });
                return key === 'ro.debuggable' ? '0' : '1';
            }
            return val;
        };
        console.log('[Root-Bypass] SystemProperties patched.');
    } catch (e) {
        console.log('[Root-Bypass] SystemProperties hook failed: ' + e.message);
    }

    console.log('[Root-Bypass] All root detection bypasses installed.');
});
