// Auto-generated by FridaScriptGenerator
// Usage: frida -U -f <package_name> -l <script.js> --no-pause
//        frida -U --attach-name <package_name> -l <script.js>

'use strict';

if (typeof Java === 'undefined') {
    console.error('[ERROR] Java bridge not available. Is this an Android process?');
} else {
    console.log('[Frida] Script loaded. Java.available=' + Java.available);
}

// Global error handler
Process.setExceptionHandler(function (ex) {
    console.error('[Frida-Exception] ' + ex.type + ' at ' + ex.address + ': ' + ex.toString());
    return false;  // don't swallow the exception
});


// ============================================================
// SSL Pinning Bypass — Frida Script (Android)
// Generated by FridaScriptGenerator
// ============================================================

'use strict';

function emit(tag, data) {
    var out = JSON.stringify({ tag: tag, data: data, ts: new Date().toISOString() });
    console.log('[FRIDA_FINDING] ' + out);
}

Java.perform(function () {

    // ── 1. Permissive TrustManager ────────────────────────────────────────
    try {
        var X509TrustManager = Java.use('javax.net.ssl.X509TrustManager');
        var SSLContext = Java.use('javax.net.ssl.SSLContext');

        var TrustAllCerts = Java.registerClass({
            name: 'com.frida.bypass.TrustAllManager',
            implements: [X509TrustManager],
            methods: {
                checkClientTrusted: function (chain, authType) { },
                checkServerTrusted: function (chain, authType) {
                    emit('ssl_bypass', { method: 'checkServerTrusted', authType: authType });
                },
                getAcceptedIssuers: function () { return []; }
            }
        });

        var sslCtx = SSLContext.getInstance('TLS');
        sslCtx.init(null, [TrustAllCerts.$new()], null);
        SSLContext.getDefault.implementation = function () {
            emit('ssl_bypass', { method: 'SSLContext.getDefault patched' });
            return sslCtx;
        };
        console.log('[SSL-Bypass] Permissive TrustManager installed.');
    } catch (e) {
        console.log('[SSL-Bypass] TrustManager bypass failed: ' + e.message);
    }

    // ── 2. OkHttp3 CertificatePinner ─────────────────────────────────────
    try {
        var CertificatePinner = Java.use('okhttp3.CertificatePinner');
        CertificatePinner.check.overload('java.lang.String', 'java.util.List').implementation = function (hostname, peerCertificates) {
            emit('ssl_bypass', { method: 'OkHttp3.CertificatePinner.check', hostname: hostname });
            console.log('[SSL-Bypass] OkHttp3 pin bypassed for: ' + hostname);
        };
        // Older overload
        CertificatePinner.check.overload('java.lang.String', '[Ljava.security.cert.Certificate;').implementation = function (hostname, certs) {
            emit('ssl_bypass', { method: 'OkHttp3.CertificatePinner.check (legacy)', hostname: hostname });
        };
        console.log('[SSL-Bypass] OkHttp3 CertificatePinner hooked.');
    } catch (e) {
        console.log('[SSL-Bypass] OkHttp3 hook failed (may not be present): ' + e.message);
    }

    // ── 3. OkHttp3 match() ────────────────────────────────────────────────
    try {
        var CertificatePinner2 = Java.use('okhttp3.CertificatePinner$Builder');
        // No-op; rely on check() override above.
    } catch (e) { }

    // ── 4. TrustManagerImpl (Conscrypt) ───────────────────────────────────
    try {
        var TrustManagerImpl = Java.use('com.android.org.conscrypt.TrustManagerImpl');
        TrustManagerImpl.verifyChain.implementation = function (untrustedChain, trustAnchorChain, host, clientAuth, ocspData, tlsSctData) {
            emit('ssl_bypass', { method: 'Conscrypt.verifyChain', host: host });
            console.log('[SSL-Bypass] Conscrypt verifyChain bypassed for: ' + host);
            return untrustedChain;
        };
        console.log('[SSL-Bypass] Conscrypt TrustManagerImpl hooked.');
    } catch (e) {
        console.log('[SSL-Bypass] Conscrypt hook failed (may not be present): ' + e.message);
    }

    // ── 5. HttpsURLConnection HostnameVerifier ────────────────────────────
    try {
        var HttpsURLConnection = Java.use('javax.net.ssl.HttpsURLConnection');
        HttpsURLConnection.setDefaultHostnameVerifier.implementation = function (verifier) {
            emit('ssl_bypass', { method: 'HttpsURLConnection.setDefaultHostnameVerifier replaced' });
            // Install permissive verifier
            var AllowAllHostnameVerifier = Java.registerClass({
                name: 'com.frida.bypass.AllHostnameVerifier',
                implements: [Java.use('javax.net.ssl.HostnameVerifier')],
                methods: {
                    verify: function (hostname, session) {
                        return true;
                    }
                }
            });
            this.setDefaultHostnameVerifier(AllowAllHostnameVerifier.$new());
        };
        console.log('[SSL-Bypass] HttpsURLConnection HostnameVerifier hooked.');
    } catch (e) {
        console.log('[SSL-Bypass] HostnameVerifier hook failed: ' + e.message);
    }

    // ── 6. Flutter SSL (native layer, best-effort) ────────────────────────
    try {
        var flutterLib = 'libflutter.so';
        var ssl_verify_ptr = Module.findExportByName(flutterLib, 'ssl_crypto_x509_session_verify_cert_chain');
        if (ssl_verify_ptr) {
            Interceptor.attach(ssl_verify_ptr, {
                onLeave: function (retval) {
                    emit('ssl_bypass', { method: 'Flutter ssl_crypto_x509_session_verify_cert_chain patched' });
                    retval.replace(1);  // return success
                }
            });
            console.log('[SSL-Bypass] Flutter SSL verify hooked.');
        }
    } catch (e) {
        console.log('[SSL-Bypass] Flutter SSL hook skipped: ' + e.message);
    }

    console.log('[SSL-Bypass] All SSL bypasses installed.');
});
