// Auto-generated by FridaScriptGenerator
// Usage: frida -U -f <package_name> -l <script.js> --no-pause
//        frida -U --attach-name <package_name> -l <script.js>

'use strict';

if (typeof Java === 'undefined') {
    console.error('[ERROR] Java bridge not available. Is this an Android process?');
} else {
    console.log('[Frida] Script loaded. Java.available=' + Java.available);
}

// Global error handler
Process.setExceptionHandler(function (ex) {
    console.error('[Frida-Exception] ' + ex.type + ' at ' + ex.address + ': ' + ex.toString());
    return false;  // don't swallow the exception
});


// ============================================================
// Storage Hook Script — SharedPreferences, Files, SQLite
// ============================================================
'use strict';

function emit(tag, data) {
    console.log('[FRIDA_FINDING] ' + JSON.stringify({ tag: tag, data: data, ts: new Date().toISOString() }));
}

var SENSITIVE_KEYS = ['password', 'passwd', 'pwd', 'token', 'secret', 'key', 'apikey',
                      'api_key', 'credential', 'auth', 'session', 'private', 'pin'];

function isSensitiveKey(k) {
    if (!k) return false;
    var lower = String(k).toLowerCase();
    return SENSITIVE_KEYS.some(function (sk) { return lower.indexOf(sk) >= 0; });
}

Java.perform(function () {

    // ── SharedPreferences.Editor ──────────────────────────────────────────
    try {
        var SharedPrefsEditor = Java.use('android.content.SharedPreferences$Editor');
        SharedPrefsEditor.putString.implementation = function (key, value) {
            if (isSensitiveKey(key)) {
                emit('sensitive_prefs_write', {
                    key: key,
                    value_preview: value ? String(value).substring(0, 40) : null,
                    risk: 'Sensitive value stored in SharedPreferences (unencrypted)'
                });
            }
            return this.putString(key, value);
        };
        SharedPrefsEditor.putInt.implementation = function (key, value) {
            if (isSensitiveKey(key)) {
                emit('sensitive_prefs_write', { key: key, value: value, type: 'int' });
            }
            return this.putInt(key, value);
        };
        SharedPrefsEditor.putBoolean.implementation = function (key, value) {
            if (isSensitiveKey(key)) {
                emit('sensitive_prefs_write', { key: key, value: value, type: 'bool' });
            }
            return this.putBoolean(key, value);
        };
        console.log('[Storage-Hook] SharedPreferences.Editor hooked.');
    } catch (e) {
        console.log('[Storage-Hook] SharedPreferences hook failed: ' + e.message);
    }

    // ── SharedPreferences.getString (read) ────────────────────────────────
    try {
        var SharedPreferences = Java.use('android.content.SharedPreferences');
        // Note: SharedPreferences is an interface; hook concrete impl
        var SharedPreferencesImpl = Java.use('android.app.SharedPreferencesImpl');
        SharedPreferencesImpl.getString.implementation = function (key, defValue) {
            var result = this.getString(key, defValue);
            if (isSensitiveKey(key) && result) {
                emit('sensitive_prefs_read', { key: key, value_preview: String(result).substring(0, 40) });
            }
            return result;
        };
    } catch (e) { /* SharedPreferencesImpl may not be accessible on all Android versions */ }

    // ── FileOutputStream ─────────────────────────────────────────────────
    try {
        var FileOutputStream = Java.use('java.io.FileOutputStream');
        FileOutputStream.$init.overload('java.lang.String').implementation = function (path) {
            if (isSensitiveKey(path)) {
                emit('sensitive_file_open', { path: path, mode: 'write' });
            }
            emit('file_open', { path: path });
            return this.$init(path);
        };
        FileOutputStream.$init.overload('java.io.File').implementation = function (file) {
            var path = file ? file.getAbsolutePath() : '';
            emit('file_open', { path: path });
            return this.$init(file);
        };
        console.log('[Storage-Hook] FileOutputStream hooked.');
    } catch (e) {
        console.log('[Storage-Hook] FileOutputStream hook failed: ' + e.message);
    }

    // ── SQLiteDatabase ────────────────────────────────────────────────────
    try {
        var SQLiteDatabase = Java.use('android.database.sqlite.SQLiteDatabase');
        SQLiteDatabase.execSQL.overload('java.lang.String').implementation = function (sql) {
            emit('sqlite_exec', { sql: String(sql).substring(0, 300) });
            return this.execSQL(sql);
        };
        SQLiteDatabase.rawQuery.overload('java.lang.String', '[Ljava.lang.String;').implementation = function (sql, args) {
            emit('sqlite_query', { sql: String(sql).substring(0, 300), args: args ? String(args) : null });
            return this.rawQuery(sql, args);
        };
        console.log('[Storage-Hook] SQLiteDatabase hooked.');
    } catch (e) {
        console.log('[Storage-Hook] SQLiteDatabase hook failed: ' + e.message);
    }

    // ── Android Keystore (read) ───────────────────────────────────────────
    try {
        var KeyStore = Java.use('java.security.KeyStore');
        KeyStore.getEntry.overload('java.lang.String', 'java.security.KeyStore$ProtectionParameter').implementation = function (alias, param) {
            emit('keystore_access', { alias: alias, operation: 'getEntry' });
            return this.getEntry(alias, param);
        };
        console.log('[Storage-Hook] KeyStore.getEntry hooked.');
    } catch (e) { }

    console.log('[Storage-Hook] All storage hooks installed.');
});
