"""Recon script generator: produces a full recon shell script for a target domain.

The script is written to disk for the tester to review and execute.
This module never sends requests directly.
"""

import os
from pathlib import Path
from oneinfinity.modules.utils import banner, section, ok, info, warn, bold

RECON_SCRIPT_TEMPLATE = '''\
#!/usr/bin/env bash
# ============================================================
#  RECON SCRIPT — {target}
#  Generated by: One&Infinity
#  Date: {date}
#
#  IMPORTANT: Review this script before running.
#  Confirm all targets are within your authorized scope.
#  YOU are responsible for ensuring authorization.
# ============================================================

set -euo pipefail

TARGET="{target}"
OUTDIR="{outdir}"
WORDLIST="${WORDLIST:-/usr/share/wordlists/dirb/common.txt}"
RATE="${RATE:-50}"   # requests per second — adjust per engagement rules

mkdir -p "$OUTDIR/recon" "$OUTDIR/recon/ports" "$OUTDIR/recon/web" "$OUTDIR/recon/js"

log() { echo "[$(date +%H:%M:%S)] $*" | tee -a "$OUTDIR/recon/recon.log"; }

# ── Confirm before starting ────────────────────────────────────────────────────
echo ""
echo "  Target  : $TARGET"
echo "  Output  : $OUTDIR/recon/"
echo ""
read -rp "  [?] Confirm scan of $TARGET? (yes/no): " ANS
[ "$ANS" = "yes" ] || { echo "  Aborted."; exit 0; }
echo ""

# ============================================================
#  PHASE 1: Subdomain Enumeration
# ============================================================
log "PHASE 1: Subdomain Enumeration"

SUBS="$OUTDIR/recon/subdomains_all.txt"

# 1a. subfinder (preferred)
if command -v subfinder &>/dev/null; then
    log "  Running subfinder..."
    subfinder -d "$TARGET" -all -silent -o "$OUTDIR/recon/subs_subfinder.txt" 2>/dev/null || true
else
    log "  [!] subfinder not found — using crt.sh fallback"
fi

# 1b. crt.sh (always run — catches what active tools miss)
log "  Querying crt.sh..."
curl -sf "https://crt.sh/?q=%.{target_bare}&output=json" 2>/dev/null | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    seen = set()
    for e in data:
        for n in e.get('name_value','').split('\\n'):
            n = n.strip().lstrip('*.')
            if n and n not in seen:
                seen.add(n)
                print(n)
except: pass
" > "$OUTDIR/recon/subs_crtsh.txt" 2>/dev/null || true

# 1c. DNS brute force (common prefixes)
log "  DNS brute forcing common prefixes..."
for prefix in www api app admin dev staging test beta uat prod internal mail vpn \\
              cdn assets static img docs portal dashboard login sso auth gateway \\
              ws graphql api2 api3 v1 v2 mobile m sandbox corp intranet; do
    result=$(dig +short "$prefix.$TARGET" 2>/dev/null | grep -v "^$" | head -1)
    [ -n "$result" ] && echo "$prefix.$TARGET" || true
done > "$OUTDIR/recon/subs_bruteforce.txt"

# Combine and deduplicate
cat "$OUTDIR/recon"/subs_*.txt 2>/dev/null | sort -u | grep -v "^$" > "$SUBS"
SUB_COUNT=$(wc -l < "$SUBS")
log "  Total unique subdomains: $SUB_COUNT"

# ============================================================
#  PHASE 2: HTTP Probing
# ============================================================
log "PHASE 2: HTTP Probing"

ALIVE="$OUTDIR/recon/alive_hosts.txt"
HTTPX_JSON="$OUTDIR/recon/httpx_results.json"

if command -v httpx &>/dev/null; then
    log "  Running httpx..."
    httpx -l "$SUBS" -status-code -title -tech-detect -content-length \\
          -web-server -follow-redirects -json -rate-limit "$RATE" \\
          -o "$HTTPX_JSON" 2>/dev/null || true
    # Extract alive hosts
    python3 -c "
import json, sys
with open('$HTTPX_JSON') as f:
    for line in f:
        try:
            d = json.loads(line)
            print(d.get('url',''))
        except: pass
" > "$ALIVE" 2>/dev/null || true
else
    log "  [!] httpx not found — using curl fallback"
    while IFS= read -r domain; do
        for scheme in https http; do
            code=$(curl -s -o /dev/null -w "%{http_code}" -m 8 -L "$scheme://$domain" 2>/dev/null || true)
            if [[ "$code" =~ ^[23] ]]; then
                echo "$scheme://$domain"
                break
            fi
        done
    done < "$SUBS" > "$ALIVE"
fi

ALIVE_COUNT=$(wc -l < "$ALIVE" 2>/dev/null || echo 0)
log "  Alive hosts: $ALIVE_COUNT"

# ============================================================
#  PHASE 3: Port Scanning (high-priority hosts)
# ============================================================
log "PHASE 3: Port Scanning"

# Scan the main target + any high-value subdomains
HIGH_VALUE=$(grep -E "(admin|api|internal|dev|staging|jenkins|kibana|grafana|console|dashboard|portal)" "$SUBS" 2>/dev/null || true)
SCAN_TARGETS="$TARGET\\n$HIGH_VALUE"

if command -v nmap &>/dev/null; then
    log "  Running nmap on high-value targets..."
    echo -e "$SCAN_TARGETS" | sort -u | while IFS= read -r host; do
        [ -z "$host" ] && continue
        log "    nmap: $host"
        nmap -sV -sC --top-ports 1000 -T3 --open \\
             -oJ "$OUTDIR/recon/ports/nmap_${host//./_}.json" \\
             "$host" 2>/dev/null || true
    done
else
    log "  [!] nmap not found — running Python TCP scanner"
    python3 << 'PYEOF'
import asyncio, json, sys

TOP_PORTS = [21,22,23,25,53,80,110,111,135,139,143,443,445,993,995,
             1723,3306,3389,5432,5900,6379,8080,8443,8888,9090,9200,9443,27017]

async def probe(host, port, timeout=3):
    try:
        _, w = await asyncio.wait_for(asyncio.open_connection(host, port), timeout=timeout)
        w.close()
        return port
    except:
        return None

async def scan(host):
    tasks = [probe(host, p) for p in TOP_PORTS]
    results = await asyncio.gather(*tasks)
    return [p for p in results if p]

target = "{target}"
open_ports = asyncio.run(scan(target))
print(f"[*] Open ports on {target}: {open_ports}")
with open("{outdir}/recon/ports/tcp_scan.json", "w") as f:
    json.dump({"host": target, "open_ports": open_ports}, f, indent=2)
PYEOF
fi

# ============================================================
#  PHASE 4: Content Discovery
# ============================================================
log "PHASE 4: Content Discovery"

INTERESTING_PATHS=(
    ".git/config" ".git/HEAD" ".git/COMMIT_EDITMSG"
    ".env" ".env.local" ".env.production" ".env.backup"
    "config.php" "wp-config.php" "config.php.bak"
    "swagger.json" "openapi.json" "api/swagger" "api/docs" "api-docs"
    "swagger-ui.html" "swagger/index.html"
    "graphql" "graphiql" "graph"
    "actuator" "actuator/env" "actuator/health" "actuator/info" "actuator/mappings"
    "phpinfo.php" "info.php" "server-status" "server-info"
    ".well-known/security.txt" "robots.txt" "sitemap.xml"
    "admin" "admin/login" "admin/dashboard" "wp-admin" "administrator"
    "console" "debug" "trace" "status" "health" "metrics"
    "backup" "backup.zip" "backup.tar.gz" "db.sql" "dump.sql"
    "package.json" "composer.json" "Dockerfile" "docker-compose.yml"
)

log "  Checking interesting paths on main target..."
BASE="https://$TARGET"
for path in "${INTERESTING_PATHS[@]}"; do
    code=$(curl -s -o /dev/null -w "%{http_code}" -m 6 "$BASE/$path" 2>/dev/null || true)
    if [[ "$code" != "404" && "$code" != "000" && "$code" != "400" ]]; then
        echo "$code $BASE/$path"
        log "  [+] $code  $path"
    fi
done > "$OUTDIR/recon/web/interesting_paths.txt"

# ffuf for broader discovery (if available)
if command -v ffuf &>/dev/null && [ -f "$WORDLIST" ]; then
    log "  Running ffuf directory discovery..."
    ffuf -u "$BASE/FUZZ" -w "$WORDLIST" \\
         -mc 200,201,204,301,302,401,403,405,500 \\
         -rate "$RATE" \\
         -json -o "$OUTDIR/recon/web/ffuf_results.json" 2>/dev/null || true
fi

# ============================================================
#  PHASE 5: JavaScript Collection & Analysis
# ============================================================
log "PHASE 5: JavaScript Collection"

JS_DIR="$OUTDIR/recon/js"

# Fetch main page and extract JS file URLs
log "  Extracting JS files from main page..."
curl -sf -m 15 "$BASE" 2>/dev/null | python3 -c "
import sys, re
html = sys.stdin.read()
scripts = re.findall(r'<script[^>]+src=[\"\\x27]([^\"\\x27>]+)[\"\\x27]', html)
for s in scripts:
    if s.startswith('//'):
        print('https:' + s)
    elif s.startswith('/'):
        print('https://{target}' + s)
    elif s.startswith('http'):
        print(s)
" > "$JS_DIR/js_urls.txt" 2>/dev/null || true

JS_COUNT=$(wc -l < "$JS_DIR/js_urls.txt" 2>/dev/null || echo 0)
log "  Found $JS_COUNT JS files — downloading..."

while IFS= read -r js_url; do
    [ -z "$js_url" ] && continue
    fname=$(echo "$js_url" | sed 's|.*/||' | sed 's/[?&=]/_/g')
    curl -sf -m 15 "$js_url" -o "$JS_DIR/$fname" 2>/dev/null || true
    # Also try source map
    curl -sf -m 10 "$js_url.map" -o "$JS_DIR/$fname.map" 2>/dev/null || true
done < "$JS_DIR/js_urls.txt"

# Grep JS files for secrets and endpoints
log "  Scanning JS for secrets and endpoints..."
if ls "$JS_DIR"/*.js &>/dev/null; then
    grep -rhoE '(api[_-]?key|apikey|secret|token|password|AWS_|AKIA)[^"'"'"'\\s]*["'"'"'\\s][^"'"'"'\\s]{8,}' \\
         "$JS_DIR"/*.js 2>/dev/null > "$JS_DIR/potential_secrets.txt" || true
    grep -rhoE '"(/api/[^"]+|/v[0-9]+/[^"]+)"' \\
         "$JS_DIR"/*.js 2>/dev/null | sort -u > "$JS_DIR/api_endpoints.txt" || true
fi

# ============================================================
#  PHASE 6: Security Headers & CORS Quick Check
# ============================================================
log "PHASE 6: Headers & CORS Quick Check"

log "  Checking security headers..."
curl -sf -I -m 10 "$BASE" 2>/dev/null > "$OUTDIR/recon/web/headers_main.txt" || true

log "  Testing CORS with evil.com origin..."
curl -sf -I -H "Origin: https://evil.com" -m 10 "$BASE" 2>/dev/null \\
     > "$OUTDIR/recon/web/cors_test.txt" || true

grep -i "access-control" "$OUTDIR/recon/web/cors_test.txt" && \\
    log "  [!] CORS headers found — review cors_test.txt" || true

# ============================================================
#  SUMMARY
# ============================================================
echo ""
echo "════════════════════════════════════════════════════════"
echo "  RECON COMPLETE — $TARGET"
echo "════════════════════════════════════════════════════════"
echo ""
echo "  Output directory : $OUTDIR/recon/"
echo "  Subdomains found : $(wc -l < "$SUBS" 2>/dev/null || echo 0)"
echo "  Alive hosts      : $(wc -l < "$ALIVE" 2>/dev/null || echo 0)"
echo "  Interesting paths: $(wc -l < "$OUTDIR/recon/web/interesting_paths.txt" 2>/dev/null || echo 0)"
echo "  JS files saved   : $(ls "$JS_DIR"/*.js 2>/dev/null | wc -l || echo 0)"
echo ""
echo "  Next steps:"
echo "    oneinfinity analyze subdomains $OUTDIR/recon/subdomains_all.txt"
echo "    oneinfinity analyze responses  $OUTDIR/recon/httpx_results.json"
echo "    oneinfinity analyze js         $OUTDIR/recon/js/*.js"
echo "    oneinfinity plan"
echo ""
log "Done."
'''


class ReconRunner:
    def __init__(self, program_dir: str):
        self.program_dir = Path(program_dir)
        self.scripts_dir = self.program_dir / "scripts"
        self.scripts_dir.mkdir(parents=True, exist_ok=True)

    def generate_script(self, target: str) -> str:
        from datetime import datetime
        from oneinfinity.modules.utils import slugify

        # Strip scheme if provided
        import re
        target_bare = re.sub(r"^https?://", "", target).split("/")[0]

        outdir = str(self.program_dir).rstrip("/")
        date   = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        # Use simple replacement to avoid conflicts with bash ${VAR} and regex {n,m} syntax
        script = RECON_SCRIPT_TEMPLATE
        script = script.replace("{target}", target_bare)
        script = script.replace("{target_bare}", target_bare)
        script = script.replace("{outdir}", outdir)
        script = script.replace("{date}", date)

        script_path = self.scripts_dir / f"recon_{target_bare.replace('.', '_')}.sh"
        script_path.write_text(script)
        script_path.chmod(0o755)
        return str(script_path)

    def show_tool_check(self):
        """Print which recon tools are available."""
        import shutil
        section("Tool Availability")
        tools = {
            "subfinder": "Subdomain enumeration (preferred)",
            "httpx":     "HTTP probing and fingerprinting",
            "nmap":      "Port scanning",
            "ffuf":      "Directory/content fuzzing",
            "dig":       "DNS queries (fallback subdomain enum)",
            "curl":      "HTTP requests (always available fallback)",
            "python3":   "Port scanning + analysis fallbacks",
        }
        for tool, purpose in tools.items():
            found = shutil.which(tool) is not None
            status = ok if found else warn
            marker = "✓" if found else "✗ (built-in fallback will be used)"
            print(f"  {'✓' if found else '✗'} {tool:<12} {purpose}")
        print()
